# Batch 1: Civil Engineering, Construction Materials & Chemicals (65 Standards)
# Total after Batch 1 = 60 + 65 = 125 standards

def cls(cid, num, title, content, test_req=None, mandatory=True):
    c = {
        "id": cid,
        "number": num,
        "title": title,
        "content": content,
        "mandatory": mandatory
    }
    if test_req:
        c["testRequirement"] = test_req
        c["testMethod"] = test_req
    return c

BATCH_1_DATA = [
    # Civil & Structural Aggregates / Concrete
    ("is-383-2016", "IS 383:2016", "Coarse and Fine Aggregate for Concrete — Specification", 2016,
     "Civil & Construction", "Civil Engineering / CED 2", True, "Scheme I (ISI Mark)", "Aggregates Quality Control Order",
     ["aggregate crushing units", "quarry operations", "ready mix concrete plants"],
     "Mandatory specification for natural, manufactured, and recycled coarse and fine aggregates for structural concrete.",
     "Covers physical and chemical requirements of natural gravel, crushed stone, and recycled aggregates.",
     ["coarse aggregate", "fine aggregate", "crushed sand", "flakiness index", "elongation index", "silt content"],
     [cls("is383-c4", "Clause 4.1", "Particle Size Distribution (Grading Zones)", "Fine aggregate shall conform to Grading Zone I, II, III, or IV sieve analysis per Table 4."),
      cls("is383-c5", "Clause 5.3", "Flakiness and Elongation Index", "Combined flakiness and elongation index for coarse aggregate shall not exceed 35% by mass.")]),

    ("is-516-2021", "IS 516:2021", "Hardened Concrete — Methods of Test (Compressive, Flexural & Split Tensile)", 2021,
     "Civil & Construction", "Civil Engineering / CED 2", True, "Scheme I (ISI Mark)", "Concrete Quality Standards",
     ["concrete testing labs", "RCC construction", "infrastructure contractors"],
     "Standard test procedures for compressive strength (150 mm cubes), flexural strength, and splitting tensile strength of hardened concrete.",
     "Prescribes sampling, moulding, curing, and compression testing of concrete specimens.",
     ["compressive strength", "cube test", "split tensile test", "flexural strength", "concrete testing"],
     [cls("is516-c5", "Clause 5.1", "Compressive Strength Determination", "150mm cubes tested at 28 days under calibrated compression testing machine at 14 MPa/min rate.")]),

    ("is-1199-2018", "IS 1199:2018", "Fresh Concrete — Methods of Sampling, Testing and Analysis (Slump Test)", 2018,
     "Civil & Construction", "Civil Engineering / CED 2", True, "Scheme I (ISI Mark)", "Ready Mix Concrete Standards",
     ["RMC batching plants", "site laboratories", "civil engineering contractors"],
     "Standard testing methods for fresh concrete workability, slump cone test, compaction factor, and fresh density.",
     "Covers procedures for determining consistency and fresh properties of structural concrete.",
     ["slump test", "fresh concrete", "workability", "compaction factor", "slump cone"],
     [cls("is1199-c4", "Clause 4.2", "Slump Cone Workability Test", "Slump measurement using standard cone (100mm top, 200mm bottom, 300mm height) tamped in 3 layers.")]),

    ("is-10262-2019", "IS 10262:2019", "Concrete Mix Proportioning — Guidelines", 2019,
     "Civil & Construction", "Civil Engineering / CED 2", False, "Scheme I (ISI Mark)", "Structural Engineering Guidelines",
     ["concrete mix designers", "civil consultants", "RMC quality control"],
     "National guidelines for proportioning concrete mixes from M10 to M100, incorporating flyash, slag, and chemical admixtures.",
     "Provides target mean strength calculations, water-cement ratios, and aggregate proportions.",
     ["mix design", "water cement ratio", "M25 M30 M40", "concrete proportioning", "durability"],
     [cls("is10262-c3", "Clause 3.2", "Target Mean Compressive Strength", "Target mean strength f'ck = fck + 1.65 s, where s is standard deviation from Table 1.")]),

    ("is-800-2007", "IS 800:2007", "General Construction in Steel — Code of Practice (Limit State Method)", 2007,
     "Civil & Construction", "Civil Engineering / CED 7", True, "Scheme I (ISI Mark)", "National Building Code",
     ["PEB manufacturers", "structural steel fabricators", "bridge construction"],
     "National code of practice for design and fabrication of structural steelwork using limit state design principles.",
     "Applies to all steel framed structures, industrial sheds, and PEB buildings.",
     ["steel design", "limit state design", "PEB structure", "welded connections", "bolted joints", "buckling"],
     [cls("is800-c5", "Clause 5.1", "Limit States of Strength and Serviceability", "Structural steel elements shall satisfy limit state of collapse (flexure, compression, shear) and deflection.")]),

    ("is-875-1-1987", "IS 875 (Part 1):1987", "Design Loads for Buildings and Structures: Part 1 Dead Loads", 1987,
     "Civil & Construction", "Civil Engineering / CED 37", True, "Scheme I (ISI Mark)", "National Building Code",
     ["structural designers", "civil consulting engineers"],
     "Code of practice specifying unit weights of building materials and stored goods for dead load calculations.",
     "Provides unit weights of masonry, concrete, metals, and timber used in building construction.",
     ["dead load", "unit weight of concrete", "building loads", "structural analysis"],
     [cls("is875-1-c3", "Clause 3.1", "Unit Weights of Building Materials", "RCC unit weight 25.0 kN/m³; plain cement concrete 24.0 kN/m³; brick masonry 19.0 kN/m³.")]),

    ("is-875-2-1987", "IS 875 (Part 2):1987", "Design Loads for Buildings and Structures: Part 2 Imposed Loads", 1987,
     "Civil & Construction", "Civil Engineering / CED 37", True, "Scheme I (ISI Mark)", "National Building Code",
     ["structural design firms", "commercial building engineers"],
     "Specifies live load and imposed load values for residential, office, institutional, industrial, and storage buildings.",
     "Covers floor live loads, roof loads, and concentrated load criteria.",
     ["imposed load", "live load", "floor load", "commercial building design"],
     [cls("is875-2-c3", "Clause 3.1", "Uniformly Distributed Imposed Floor Loads", "Residential rooms: 2.0 kN/m²; office general floors: 3.0 kN/m²; storage warehouses: 5.0 kN/m² minimum.")]),

    ("is-875-3-2015", "IS 875 (Part 3):2015", "Design Loads for Buildings and Structures: Part 3 Wind Loads", 2015,
     "Civil & Construction", "Civil Engineering / CED 37", True, "Scheme I (ISI Mark)", "National Building Code",
     ["wind engineering consultants", "PEB structure design", "tower manufacturers"],
     "Specifies wind zones of India (33 m/s to 55 m/s basic wind speed), terrain categories, and gust aerodynamic design pressures.",
     "Covers calculation of design wind pressure Vz and design wind force on structures.",
     ["wind load", "basic wind speed", "terrain category", "aerodynamic factor", "cyclone resistant"],
     [cls("is875-3-c6", "Clause 6.3", "Design Wind Speed (Vz)", "Vz = Vb * k1 (risk) * k2 (terrain) * k3 (topography) * k4 (cyclonic factor).")]),

    ("is-1893-1-2016", "IS 1893 (Part 1):2016", "Criteria for Earthquake Resistant Design of Structures: Part 1 General Provisions", 2016,
     "Civil & Construction", "Civil Engineering / CED 39", True, "Scheme I (ISI Mark)", "Earthquake Safety Mandate",
     ["structural earthquake engineers", "high-rise building developers"],
     "Mandatory standard for seismic zoning of India (Zones II to V), response reduction factors, and design acceleration spectra.",
     "Covers earthquake design principles for buildings, foundations, and non-structural elements.",
     ["earthquake resistant", "seismic zone V", "base shear", "response spectrum", "drift limitation"],
     [cls("is1893-c6", "Clause 6.4", "Design Horizontal Seismic Coefficient (Ah)", "Ah = (Z * I * Sa/g) / (2 * R), where Z is seismic zone factor and R is response reduction factor.")]),

    ("is-13920-2016", "IS 13920:2016", "Ductile Design and Detailing of Reinforced Concrete Structures Subjected to Seismic Forces", 2016,
     "Civil & Construction", "Civil Engineering / CED 39", True, "Scheme I (ISI Mark)", "National Building Code",
     ["RCC detailing engineers", "high-rise residential construction"],
     "Mandatory detailing rules for beam-column joints, confinement ties, shear wall reinforcement, and lap splices in seismic zones.",
     "Applies to reinforced concrete structures located in seismic zones III, IV, and V.",
     ["ductile detailing", "confinement ties", "seismic detailing", "beam column joint", "lap splice"],
     [cls("is13920-c7", "Clause 7.4", "Special Confinement Reinforcement in Columns", "Closely spaced rectangular links/spirals required at column ends with pitch not exceeding 100mm.")]),

    ("is-1077-1992", "IS 1077:1992", "Common Burnt Clay Building Bricks — Specification", 1992,
     "Civil & Construction", "Civil Engineering / CED 30", True, "Scheme I (ISI Mark)", "Clay Bricks Quality Standards",
     ["brick kilns", "clay brick manufacturing", "masonry contractors"],
     "Specifies physical and compressive strength classes (3.5 MPa to 35 MPa), dimensions, and efflorescence for clay bricks.",
     "Covers dimensional tolerances, water absorption, and crushing strength of burnt clay bricks.",
     ["clay brick", "compressive strength", "water absorption", "efflorescence", "brick kiln"],
     [cls("is1077-c6", "Clause 6.1", "Compressive Strength Classes", "Class 3.5 minimum 3.5 MPa; Class 7.5 minimum 7.5 MPa; Class 10 minimum 10.0 MPa; water absorption <= 20%.")]),

    ("is-2185-1-2005", "IS 2185 (Part 1):2005", "Concrete Masonry Units — Specification: Part 1 Hollow and Solid Concrete Blocks", 2005,
     "Civil & Construction", "Civil Engineering / CED 30", True, "Scheme I (ISI Mark)", "Concrete Blocks Quality Order",
     ["concrete block plants", "hollow block manufacturing", "masonry unit suppliers"],
     "Specifies dimensions, minimum block density, compressive strength, and water absorption for hollow and solid concrete blocks.",
     "Covers solid and hollow load-bearing and non-load bearing concrete masonry blocks.",
     ["hollow block", "solid concrete block", "masonry unit", "compressive strength", "block density"],
     [cls("is2185-1-c8", "Clause 8.1", "Compressive Strength of Concrete Blocks", "Grade A load-bearing blocks shall have minimum compressive strength of 3.5 to 15.0 MPa.")]),

    ("is-2185-2-1983", "IS 2185 (Part 2):1983", "Concrete Masonry Units — Specification: Part 2 Autoclaved Cellular Aerated Concrete Blocks (AAC)", 1983,
     "Civil & Construction", "Civil Engineering / CED 30", True, "Scheme I (ISI Mark)", "AAC Blocks Quality Order",
     ["AAC block plants", "autoclave block manufacturing", "lightweight masonry"],
     "Specifies dry density grades, compressive strength, and thermal conductivity for autoclaved aerated concrete (AAC) blocks.",
     "Covers manufacture and quality requirements of AAC blocks for lightweight thermal-efficient walls.",
     ["AAC block", "autoclaved aerated concrete", "dry density", "thermal insulation", "crushing strength"],
     [cls("is2185-2-c6", "Clause 6.1", "Density and Compressive Strength of AAC", "Grade 1 AAC dry density 551-650 kg/m³, minimum compressive strength >= 4.0 MPa; thermal conductivity <= 0.24 W/m-K.")]),

    ("is-3495-1992", "IS 3495 (Parts 1 to 4):2019", "Methods of Tests of Burnt Clay Building Bricks", 2019,
     "Civil & Construction", "Civil Engineering / CED 30", True, "Scheme I (ISI Mark)", "Testing Standards",
     ["brick testing labs", "civil quality testing"],
     "Prescribes standardized methods for compressive strength, water absorption, efflorescence, and warpage of bricks.",
     "Covers laboratory test procedures for all types of building bricks.",
     ["brick testing", "efflorescence test", "water absorption 24h", "crushing test"],
     [cls("is3495-c2", "Clause 2.1", "Efflorescence Examination", "Bricks soaked in distilled water and dried; efflorescence rated as Nil, Slight, Moderate, Heavy or Serious.")]),

    # Fasteners & Steel Pipes
    ("is-1363-1-2019", "IS 1363 (Part 1):2019", "Hexagon Head Bolts, Screws and Nuts (Grade C) — Part 1: Hexagon Head Bolts", 2019,
     "Civil & Construction", "Mechanical / PGD 31", True, "Scheme I (ISI Mark)", "Fasteners Quality Control Order",
     ["bolt and nut manufacturing", "fastener factories", "steel fastener plants"],
     "Mandatory standard for coarse black hexagon head bolts in sizes M5 to M64 for structural and general engineering assemblies.",
     "Covers dimensions, thread tolerances, and mechanical property grades for Grade C bolts.",
     ["hex bolt", "structural bolt", "Grade 4.6", "tensile proof load", "fasteners QCO"],
     [cls("is1363-c5", "Clause 5.1", "Mechanical Properties (Grade 4.6 & 4.8)", "Tensile strength >= 400 MPa, yield stress >= 240 MPa, minimum elongation >= 22% per IS 1367.")]),

    ("is-1367-1-2018", "IS 1367 (Part 1):2018", "Technical Supply Conditions for Threaded Steel Fasteners — General Requirements", 2018,
     "Civil & Construction", "Mechanical / PGD 31", True, "Scheme I (ISI Mark)", "Fasteners Quality Control Order",
     ["cold forging fastener plants", "heat treatment shops"],
     "General requirements, surface defects, electroplating tolerances, and inspection for threaded steel bolts and screws.",
     "Covers technical supply conditions for all carbon and alloy steel threaded fasteners.",
     ["fastener inspection", "decarburization", "hydrogen embrittlement", "surface crack test"],
     [cls("is1367-c4", "Clause 4.3", "Surface Discontinuities & Cracks", "Fasteners must be free from seams, quench cracks, and shear bursts exceeding limits of IS 1367 (Part 9).")]),

    ("is-1239-1-2014", "IS 1239 (Part 1):2014", "Steel Tubes, Tubulars and Other Wrought Steel Fittings — Part 1: Steel Tubes (MS Pipes)", 2014,
     "Civil & Construction", "Metallurgical / MTD 19", True, "Scheme I (ISI Mark)", "Steel Tubes Quality Control Order",
     ["MS pipe mills", "ERW steel tube manufacturing", "galvanized pipe plants"],
     "Mandatory standard for Electric Resistance Welded (ERW) and seamless mild steel pipes in Light, Medium, and Heavy classes (GI & Black).",
     "Covers mild steel tubes from 15 mm to 150 mm nominal bore for water, gas, and plumbing conveyance.",
     ["MS pipe", "GI pipe", "ERW tube", "hydrostatic test 5MPa", "flattening test", "zinc coating 360g/m²"],
     [cls("is1239-1-c8", "Clause 8.1", "Hydraulic Test & Flattening Test", "Every pipe proof tested at 5.0 MPa hydrostatic pressure for 5 seconds; ERW weld seam flattening without cracking.")]),

    ("is-1239-2-2011", "IS 1239 (Part 2):2011", "Mild Steel Tubulars and Other Wrought Steel Pipe Fittings", 2011,
     "Civil & Construction", "Metallurgical / MTD 19", True, "Scheme I (ISI Mark)", "Steel Pipe Fittings QCO",
     ["pipe fitting manufacturers", "GI elbow and tee factories"],
     "Mandatory standard for galvanized and black steel pipe fittings: sockets, elbows, tees, unions, and nipples up to 150 mm NB.",
     "Covers threaded wrought steel and malleable pipe fittings for water and steam systems.",
     ["pipe fittings", "GI elbow", "GI tee", "pipe socket", "pipe union", "pressure rating"],
     [cls("is1239-2-c5", "Clause 5.1", "Pressure and Leakage Resistance", "Fittings shall withstand internal pneumatic pressure of 0.5 MPa immersed in water without leakage.")]),

    ("is-3589-2001", "IS 3589:2001", "Steel Pipes for Water and Sewage (168.3 mm to 2540 mm Outside Diameter)", 2001,
     "Civil & Construction", "Metallurgical / MTD 19", True, "Scheme I (ISI Mark)", "Steel Quality Control Order",
     ["spiral welded pipe mills", "large diameter water transmission pipes"],
     "Mandatory standard for Submerged Arc Welded (SAW) and ERW large diameter steel trunk water pipes (Fe 330, Fe 410, Fe 450).",
     "Covers manufacturing, internal epoxy/cement lining, and external coating for municipal bulk water mains.",
     ["large diameter pipe", "SAW pipe", "spiral welded pipe", "bulk water pipeline", "hydrostatic proof 7MPa"],
     [cls("is3589-c9", "Clause 9.1", "Mill Hydrostatic Proof Test", "Each pipe tested to hydrostatic pressure generating minimum 60% of specified yield stress without rupture.")]),

    ("is-432-1-1982", "IS 432 (Part 1):1982", "Mild Steel and Medium Tensile Steel Bars and Hard-Drawn Steel Wire for Concrete Reinforcement", 1982,
     "Civil & Construction", "Metallurgical / MTD 4", True, "Scheme I (ISI Mark)", "Steel Quality Control Order",
     ["re-rolling mills", "mild steel bar rolling", "dowel bar manufacturing"],
     "Mandatory standard for Grade I and Grade II plain round mild steel bars used for dowels, ties, and RCC reinforcement.",
     "Covers mechanical and chemical requirements of plain round steel bars.",
     ["mild steel bar", "plain round rebar", "Fe 250", "dowel bar", "tensile strength"],
     [cls("is432-c6", "Clause 6.1", "Tensile and Bend Test", "Minimum yield stress >= 250 MPa, ultimate tensile strength >= 410 MPa, elongation >= 23% with 180° cold bend.")]),

    ("is-280-2006", "IS 280:2006", "Mild Steel Wire for General Engineering Purposes (Binding Wire & Galvanized Wire)", 2006,
     "Civil & Construction", "Metallurgical / MTD 4", True, "Scheme I (ISI Mark)", "Steel Wire Quality Control Order",
     ["wire drawing units", "binding wire manufacturing", "GI wire plants"],
     "Mandatory standard for annealed mild steel binding wire and galvanized commercial wire (0.12 mm to 10.0 mm diameter).",
     "Covers wire drawing, annealing, zinc coating mass, and tensile property tolerances.",
     ["binding wire", "annealed wire", "GI wire", "zinc coating", "wire drawing", "tensile strength"],
     [cls("is280-c5", "Clause 5.1", "Tensile Strength & Ductility (Annealed)", "Tensile strength of annealed binding wire 300 to 450 MPa; must withstand wrapping round its own diameter.")]),

    ("is-1161-2014", "IS 1161:2014", "Steel Tubes for Structural Purposes — Specification", 2014,
     "Civil & Construction", "Metallurgical / MTD 19", True, "Scheme I (ISI Mark)", "Steel Tubes Quality Control Order",
     ["structural tube mills", "scaffolding pipe manufacturers", "truss fabrication"],
     "Mandatory standard for hot-finished and cold-formed ERW structural circular hollow sections (YSt 210, YSt 240, YSt 310).",
     "Covers circular structural steel tubes used for roof trusses, columns, and scaffolding.",
     ["structural steel tube", "circular hollow section", "YSt 310", "scaffolding pipe", "tensile yield"],
     [cls("is1161-c8", "Clause 8.1", "Tensile Requirements & Elongation", "Grade YSt 310: Yield strength >= 310 MPa, tensile strength >= 450 MPa, elongation >= 14% on gauge length.")]),

    ("is-4923-2017", "IS 4923:2017", "Hollow Steel Sections for Structural Use (RHS and SHS) — Specification", 2017,
     "Civil & Construction", "Metallurgical / MTD 19", True, "Scheme I (ISI Mark)", "Steel Tubes Quality Control Order",
     ["square hollow section plants", "RHS SHS tube mills", "PEB structure fabrication"],
     "Mandatory standard for Rectangular Hollow Sections (RHS) and Square Hollow Sections (SHS) for architectural frames and structural trusses.",
     "Covers cold formed and welded carbon steel hollow sections from 20x20 mm up to 400x400 mm.",
     ["RHS", "SHS", "square hollow section", "rectangular tube", "PEB truss", "corner radius"],
     [cls("is4923-c9", "Clause 9.1", "Dimensional & Sectional Tolerances", "Corner radius <= 3t; twisting <= 2.0 mm/m; concavity/convexity <= 0.8% of outer dimension.")]),

    ("is-11587-1986", "IS 11587:1986", "Structural Weathering Steel — Specification", 1986,
     "Civil & Construction", "Metallurgical / MTD 4", True, "Scheme I (ISI Mark)", "Steel Quality Control Order",
     ["bridge fabrication", "architectural steel rolling", "transmission tower manufacturing"],
     "Mandatory standard for atmospheric corrosion-resistant weathering steel plates and sections (Corten equivalent).",
     "Covers steel possessing self-passivating oxide barrier patina against atmospheric corrosion.",
     ["weathering steel", "corten steel", "atmospheric corrosion", "bridge steel", "patina"],
     [cls("is11587-c5", "Clause 5.1", "Atmospheric Corrosion Resistance Index", "Corrosion index >= 6.0 based on ASTM G101 calculated from Cu, Cr, Ni, and P elemental composition.")]),

    ("is-808-2021", "IS 808:2021", "Dimensions for Hot Rolled Steel Beam, Column, Channel and Angle Sections", 2021,
     "Civil & Construction", "Metallurgical / MTD 4", True, "Scheme I (ISI Mark)", "Steel Quality Control Order",
     ["hot rolling mills", "steel plants", "structural steel stockyards"],
     "Standard dimensions, sectional weights, and geometric properties of Indian Standard Beams (ISMB/ISJB), Columns (ISMC), and Angles (ISA).",
     "Covers standard profiles for hot rolled structural steel shapes.",
     ["ISMB", "I beam", "ISMC channel", "ISA angle", "sectional weight", "moment of inertia"],
     [cls("is808-c3", "Clause 3.1", "Standard Sectional Dimensions and Tolerances", "Nominal dimensions, flange thickness, web thickness, and mass per meter shall conform to Tables 1 through 6.")]),

    ("is-1732-1989", "IS 1732:1989", "Dimensions for Round and Square Steel Bars for Structural and Engineering Purposes", 1989,
     "Civil & Construction", "Metallurgical / MTD 4", True, "Scheme I (ISI Mark)", "Steel Quality Control Order",
     ["bright bar units", "forging raw material suppliers", "steel stockists"],
     "Standard dimensions and mass per linear meter for hot-rolled round and square carbon steel bars.",
     "Covers bar sizes from 5 mm to 250 mm for engineering machining and structural uses.",
     ["round bar", "square steel bar", "dimensional tolerance", "forging steel"],
     [cls("is1732-c3", "Clause 3.2", "Mass and Ovality Tolerances", "Weight tolerance ±2.5% to ±5%; ovality (difference between max and min diameter) <= 75% of tolerance band.")]),

    ("is-1852-1985", "IS 1852:1985", "Rolling and Cutting Tolerances for Hot Rolled Steel Products", 1985,
     "Civil & Construction", "Metallurgical / MTD 4", True, "Scheme I (ISI Mark)", "Steel Quality Control Order",
     ["steel mills", "shearing and cutting centres", "structural steel yards"],
     "Standard permissible deviations in length, width, thickness, camber, sweep, and squareness for rolled steel.",
     "Covers dimensional tolerances for steel plates, sheets, flats, beams, channels, and angles.",
     ["rolling tolerance", "camber", "sweep", "cutting length tolerance", "camber of beam"],
     [cls("is1852-c8", "Clause 8.1", "Camber and Sweep Tolerances", "Camber of beams and channels shall not exceed 0.20% of the span length.")]),

    ("is-513-1-2016", "IS 513 (Part 1):2016", "Cold Reduced Low Carbon Steel Sheets and Strips — Part 1: Cold Forming and Drawing Steel", 2016,
     "Civil & Construction", "Metallurgical / MTD 4", True, "Scheme I (ISI Mark)", "Steel Quality Control Order",
     ["CRCA sheet processing", "automobile stampings", "appliances cabinet manufacturing"],
     "Mandatory standard for Cold Rolled Close Annealed (CRCA) steel sheets (CR1 to CR5 grades) for deep drawing and automotive stamping.",
     "Covers cold rolled carbon steel sheets from 0.18 mm to 3.20 mm thickness.",
     ["CRCA sheet", "cold rolled steel", "deep drawing", "Erichsen cupping value", "plastic strain ratio r-bar"],
     [cls("is513-c6", "Clause 6.1", "Erichsen Cupping and Tensile Properties", "CR4 grade: yield strength 140-210 MPa; tensile 270-350 MPa; minimum elongation 38%; Erichsen cupping >= 10.5 mm.")]),

    ("is-277-2018", "IS 277:2018", "Galvanized Steel Sheets (Plain and Corrugated) — Specification", 2018,
     "Civil & Construction", "Metallurgical / MTD 4", True, "Scheme I (ISI Mark)", "Galvanized Steel Quality Control Order",
     ["continuous galvanizing lines (CGL)", "roofing sheet plants", "duct manufacturing"],
     "Mandatory standard for hot-dip zinc coated plain and corrugated steel sheets (GP & GC) with coating mass from 90 to 600 g/m².",
     "Covers galvanized carbon steel sheets for roofing, cladding, and HVAC ductwork.",
     ["GI sheet", "galvanized sheet", "corrugated roofing", "zinc coating mass", "spangle", "triple spot test"],
     [cls("is277-c6", "Clause 6.1", "Zinc Coating Mass Determination (Triple Spot Test)", "Class 120 zinc coating >= 120 g/m²; Class 275 >= 275 g/m² (both sides total) per IS 6745.")]),

    ("is-14246-2013", "IS 14246:2013", "Continuously Pre-Painted Galvanized Steel Sheets and Coils — Specification", 2013,
     "Civil & Construction", "Metallurgical / MTD 4", True, "Scheme I (ISI Mark)", "Color Coated Steel Quality Control Order",
     ["color coating coil lines", "PEB cladding roll forming plants"],
     "Mandatory standard for pre-painted galvanized (PPGI) and Galvalume roofing sheets with polyester or PVDF protective top coats.",
     "Covers aesthetic pre-painted steel sheets used for building roofing, facades, and wall cladding.",
     ["PPGI sheet", "color coated roofing", "dry film thickness DFT", "cross hatch adhesion", "salt spray test 1000h"],
     [cls("is14246-c7", "Clause 7.1", "Paint Film Thickness and Flexibility (T-Bend)", "Top coat DFT >= 20 microns; primer >= 5 microns; T-bend flexibility <= 3T without micro-cracking.")]),

    ("is-15911-2010", "IS 15911:2010", "Structural Steel for Fire Resistant Applications — Specification", 2010,
     "Civil & Construction", "Metallurgical / MTD 4", True, "Scheme I (ISI Mark)", "Steel Quality Control Order",
     ["fire rated steel manufacturing", "high-rise skyscraper fabrication"],
     "Mandatory standard for thermo-mechanically treated structural steel retaining at least two-thirds of yield strength at 600°C.",
     "Covers fire-resistant steel plates, beams, and columns for multi-storey high-occupancy structures.",
     ["fire resistant steel", "high temperature yield strength", "600°C strength", "fire safety steel"],
     [cls("is15911-c6", "Clause 6.2", "Elevated Temperature Yield Strength", "Yield strength at 600°C shall not be less than 67% of specified room temperature minimum yield strength.")]),

    # Timber, Plywood & Ceramic Tiles
    ("is-303-1989", "IS 303:1989", "Plywood for General Purposes — Specification (MR and BWR Grades)", 1989,
     "Civil & Construction", "Civil Engineering / CED 20", True, "Scheme I (ISI Mark)", "Plywood Quality Control Order",
     ["plywood factories", "veneer peeling plants", "furniture core manufacturing"],
     "Mandatory specification for Moisture Resistant (MR) and Boiling Water Resistant (BWR) commercial plywood.",
     "Covers timber species, urea/phenol formaldehyde adhesives, moisture limits, and glue shear strength.",
     ["plywood", "MR grade", "BWR grade", "glue shear strength", "mycological test"],
     [cls("is303-c6", "Clause 6.1", "Glue Shear Strength & Water Resistance", "MR grade: cold water soak 16h with shear strength >= 1000 N; BWR grade: boiling water soak 8h without delamination.")]),

    ("is-710-2010", "IS 710:2010", "Marine Plywood — Specification", 2010,
     "Civil & Construction", "Civil Engineering / CED 20", True, "Scheme I (ISI Mark)", "Plywood Quality Control Order",
     ["marine plywood manufacturers", "boat building wood suppliers", "luxury modular kitchen core"],
     "Mandatory standard for premium exterior marine plywood bonded with unextended phenol formaldehyde resin, enduring 72h boiling.",
     "Covers marine grade timber panels resistant to water, fungi, wood borers, and marine organisms.",
     ["marine plywood", "BWP grade", "72 hour boiling test", "phenol formaldehyde", "glue line shear"],
     [cls("is710-c8", "Clause 8.1", "72-Hour Boiling Water Proof Test (BWP)", "Specimens boiled continuously in water for 72 hours; dry shear strength after boiling shall not be less than 1350 N.")]),

    ("is-1659-2004", "IS 1659:2004", "Blockboards — Specification", 2004,
     "Civil & Construction", "Civil Engineering / CED 20", True, "Scheme I (ISI Mark)", "Wood Panels Quality Control Order",
     ["blockboard manufacturing", "wooden door shutter core plants"],
     "Mandatory standard for solid wooden core blockboards for interior and exterior furniture and panelling.",
     "Covers softwood/hardwood battens, face veneers, dimensional squareness, and modulus of rupture.",
     ["blockboard", "wood core", "modulus of rupture", "bending strength", "screw withdrawal force"],
     [cls("is1659-c7", "Clause 7.2", "Modulus of Rupture & Screw Holding", "Modulus of rupture along grain >= 30.0 MPa; across grain >= 15.0 MPa; screw withdrawal resistance >= 1200 N.")]),

    ("is-2202-1-1999", "IS 2202 (Part 1):1999", "Wooden Flush Door Shutters (Solid Core Type) — Specification", 1999,
     "Civil & Construction", "Civil Engineering / CED 20", True, "Scheme I (ISI Mark)", "Doors Quality Control Order",
     ["flush door factories", "wooden door manufacturers"],
     "Mandatory standard for plywood/blockboard faced solid core flush doors for residential and commercial entrance installations.",
     "Covers slam tests, edge loading, end immersion, and impact resistance.",
     ["flush door", "solid core door", "slam test", "end immersion test", "impact resistance"],
     [cls("is2202-1-c7", "Clause 7.3", "Door Slamming and Impact Resistance", "Door shutter subjected to 100 consecutive severe slamming cycles without splitting of stiles, rails, or face delamination.")]),

    ("is-12823-2015", "IS 12823:2015", "Pre-laminated Particle Boards — Specification", 2015,
     "Civil & Construction", "Civil Engineering / CED 20", True, "Scheme I (ISI Mark)", "Wood Panels Quality Control Order",
     ["prelam board plants", "modular furniture raw material", "particle board manufacturing"],
     "Mandatory standard for melamine faced pre-laminated wood particle boards (Interior & Exterior Grade).",
     "Covers abrasion resistance, steam resistance, cigarette burn resistance, and surface adhesion.",
     ["prelaminated board", "particle board", "melamine paper", "abrasion cycles", "surface soundness"],
     [cls("is12823-c7", "Clause 7.1", "Surface Abrasion & Resistance to Steam", "Surface shall resist at least 350 Taber abrasion cycles; surface unchanged after 1 hour boiling steam exposure.")]),

    ("is-14587-1999", "IS 14587:1999", "Prelaminated Medium Density Fibreboard (MDF) — Specification", 1999,
     "Civil & Construction", "Civil Engineering / CED 20", True, "Scheme I (ISI Mark)", "Wood Panels Quality Control Order",
     ["MDF manufacturing plants", "interior board laminators"],
     "Mandatory standard for pre-laminated MDF panels engineered from wood fibres consolidated under high heat and pressure.",
     "Covers density, internal bond strength, thickness swelling, and screw withdrawal strength.",
     ["MDF", "medium density fibreboard", "internal bond", "thickness swelling 24h", "prelaminated MDF"],
     [cls("is14587-c6", "Clause 6.1", "Internal Bond Strength & Density", "MDF density 650 to 900 kg/m³; internal bond tensile perpendicular to surface >= 0.60 MPa; 24h thickness swelling <= 10%.")]),

    ("is-13753-1993", "IS 13753:1993", "Dust Pressed Ceramic Tiles with Water Absorption E <= 0.5% (Vitrified Tiles)", 1993,
     "Civil & Construction", "Civil Engineering / CED 5", True, "Scheme I (ISI Mark)", "Ceramic Tiles Quality Control Order",
     ["vitrified tile factories", "porcelain tile manufacturing"],
     "Mandatory standard for vitrified and porcelain floor tiles with water absorption strictly below 0.5%.",
     "Covers modulus of rupture (MOR), breaking strength, scratch hardness (Mohs), and chemical stain resistance.",
     ["vitrified tile", "porcelain tile", "water absorption 0.5%", "modulus of rupture 35MPa", "Mohs hardness"],
     [cls("is13753-c5", "Clause 5.1", "Water Absorption and Breaking Strength", "Water absorption <= 0.5%; breaking strength >= 1300 N; modulus of rupture >= 35.0 N/mm²; scratch hardness >= 6 Mohs.")]),

    ("is-15622-2017", "IS 15622:2017", "Pressed Ceramic Tiles — Specification (Glazed Wall & Floor Tiles)", 2017,
     "Civil & Construction", "Civil Engineering / CED 5", True, "Scheme I (ISI Mark)", "Ceramic Tiles Quality Control Order",
     ["ceramic wall tile plants", "glazed floor tile kilns"],
     "Mandatory standard classifying ceramic tiles into Groups BIa, BIb, BIIa, BIIb, and BIII based on shaping and water absorption.",
     "Covers glazed ceramic wall tiles, rustic floor tiles, thermal shock, and crazing resistance.",
     ["ceramic tiles", "glazed wall tile", "crazing resistance autoclave", "thermal shock", "breaking strength"],
     [cls("is15622-c8", "Clause 8.2", "Crazing Resistance in Autoclave", "Glazed tiles subjected to 1.0 MPa steam pressure in autoclave for 2 hours without developing surface crazing cracks.")]),

    # Specialized Cements & Mortars
    ("is-12269-2015", "IS 12269:2015", "53 Grade Ordinary Portland Cement — High Strength Specification", 2015,
     "Civil & Construction", "Civil Engineering / CED 2", True, "Scheme I (ISI Mark)", "Cement Quality Control Order",
     ["high grade cement production", "precast concrete girder casting"],
     "Mandatory standard for high early strength 53-grade OPC used in prestressed concrete bridges and high-rise RCC columns.",
     "Specifies physical and chemical limits: tricalcium silicate content, Blaine fineness, and setting times.",
     ["53 grade cement", "OPC 53", "high early strength", "prestressed concrete", "soundness Le Chatelier"],
     [cls("is12269-c6", "Clause 6.1", "Compressive Strength (72h, 168h, 672h)", "Compressive strength: 72 hours >= 27.0 MPa; 168 hours >= 37.0 MPa; 672 hours (28 days) >= 53.0 MPa.")]),

    ("is-8041-1990", "IS 8041:1990", "Rapid Hardening Portland Cement — Specification", 1990,
     "Civil & Construction", "Civil Engineering / CED 2", True, "Scheme I (ISI Mark)", "Cement Quality Control Order",
     ["rapid hardening cement mills", "emergency road repair materials"],
     "Mandatory standard for rapid hardening cement achieving 3-day strength equal to 7-day OPC strength.",
     "Covers high specific surface area cement for cold weather concreting and rapid formwork turnover.",
     ["rapid hardening cement", "Blaine fineness 3250", "early formwork stripping", "compressive strength 1-day"],
     [cls("is8041-c5", "Clause 5.1", "1-Day and 3-Day Compressive Strength", "Specific surface >= 3250 cm²/g; compressive strength: 24h >= 16.0 MPa; 72h >= 27.0 MPa.")]),

    ("is-455-2015", "IS 455:2015", "Portland Slag Cement — Specification (PSC)", 2015,
     "Civil & Construction", "Civil Engineering / CED 2", True, "Scheme I (ISI Mark)", "Cement Quality Control Order",
     ["slag cement manufacturing", "steel slag grinding plants"],
     "Mandatory standard for eco-friendly Portland Slag Cement blended with 25% to 70% granulated blast furnace slag.",
     "Covers high chemical resistance cement for marine constructions, coastal foundations, and sewer treatments.",
     ["slag cement", "PSC", "blast furnace slag", "marine foundation", "sulfate resistance"],
     [cls("is455-c5", "Clause 5.1", "Slag Proportion & 28-Day Strength", "Granulated blast furnace slag content between 25% and 70% by mass; 28-day compressive strength >= 33.0 MPa.")]),

    ("is-12330-1988", "IS 12330:1988", "Sulfate Resisting Portland Cement — Specification (SRC)", 1988,
     "Civil & Construction", "Civil Engineering / CED 2", True, "Scheme I (ISI Mark)", "Cement Quality Control Order",
     ["specialty cement plants", "saline soil foundation construction"],
     "Mandatory standard for cement formulated with tricalcium aluminate (C3A) limited to maximum 5.0% to resist sulfate attacks.",
     "Covers marine works, foundations in saline groundwater, and effluent treatment tank concrete.",
     ["sulfate resisting cement", "SRC", "C3A <= 5%", "sulfate attack", "saline soil concrete"],
     [cls("is12330-c4", "Clause 4.1", "Chemical Composition (C3A Limit)", "Tricalcium aluminate (C3A) shall not exceed 5.0% by mass; 28-day compressive strength >= 33.0 MPa.")]),

    ("is-6452-1989", "IS 6452:1989", "High Alumina Cement for Structural Use — Specification", 1989,
     "Civil & Construction", "Civil Engineering / CED 2", True, "Scheme I (ISI Mark)", "Cement Quality Control Order",
     ["refractory cement production", "high temperature kiln castables"],
     "Mandatory standard for monocalcium aluminate cement resisting chemical attacks and temperatures up to 1400°C.",
     "Covers bauxite-derived cement for refractory furnaces and chemical containment floors.",
     ["high alumina cement", "refractory cement", "1400°C resistance", "bauxite cement"],
     [cls("is6452-c5", "Clause 5.1", "Alumina Content and Strength", "Alumina content (Al2O3) >= 32.0%; 1-day compressive strength >= 30.0 MPa; 3-day strength >= 35.0 MPa.")]),

    ("is-3466-1988", "IS 3466:1988", "Masonry Cement — Specification", 1988,
     "Civil & Construction", "Civil Engineering / CED 2", True, "Scheme I (ISI Mark)", "Cement Quality Control Order",
     ["masonry mortar plants", "pre-mixed dry mortar manufacturers"],
     "Mandatory standard for air-entrained hydraulic cement engineered specifically for brick and stone masonry work.",
     "Covers high-workability masonry cement with high water retention and reduced cracking.",
     ["masonry cement", "plastering cement", "water retention >= 70%", "air content"],
     [cls("is3466-c5", "Clause 5.1", "Water Retention and Air Content", "Water retention shall be not less than 70%; air content of fresh mortar between 12% and 24% by volume.")]),

    ("is-1542-1992", "IS 1542:1992", "Sand for Plaster — Specification", 1992,
     "Civil & Construction", "Civil Engineering / CED 2", True, "Scheme I (ISI Mark)", "Plastering Materials Standards",
     ["sand screening plants", "plastering mortar suppliers"],
     "Specifies grading limits, particle size, and silt content for natural and crushed stone sand used for internal/external wall plaster.",
     "Covers clay and fine silt tolerances to prevent shrinkage cracks in finished wall plastering.",
     ["sand for plaster", "silt content <= 3%", "plaster sand grading", "wall rendering"],
     [cls("is1542-c5", "Clause 5.1", "Silt and Clay Impurities", "Total silt and clay content determined by sedimentation method shall not exceed 3.0% by mass.")]),

    ("is-2116-1980", "IS 2116:1980", "Sand for Masonry Mortars — Specification", 1980,
     "Civil & Construction", "Civil Engineering / CED 2", True, "Scheme I (ISI Mark)", "Masonry Materials Standards",
     ["quarry screening operations", "masonry sand suppliers"],
     "Specifies grading, maximum particle size (4.75 mm), and impurities for sand used in load-bearing brick and block masonry mortars.",
     "Covers physical characteristics of mortar sands to ensure bond strength and joint stability.",
     ["masonry sand", "mortar sand", "grading curve", "fineness modulus", "brick joint mortar"],
     [cls("is2116-c4", "Clause 4.1", "Fineness Modulus & Particle Distribution", "Fineness modulus of masonry sand between 1.5 and 3.0; passing 4.75mm sieve 100%, passing 150 micron 0-15%.")]),

    ("is-3370-1-2009", "IS 3370 (Part 1):2009", "Concrete Structures for Storage of Liquids — Code of Practice: Part 1 General Requirements", 2009,
     "Civil & Construction", "Civil Engineering / CED 38", True, "Scheme I (ISI Mark)", "Water Retaining Structures Code",
     ["water tank design engineers", "STP and ETP construction firms"],
     "Code of practice governing crack width limits (0.1 mm to 0.2 mm) and impermeability for water storage reservoirs.",
     "Covers design and construction of reinforced and prestressed concrete liquid holding tanks.",
     ["water tank design", "crack width 0.1mm", "liquid retaining structure", "impermeable concrete"],
     [cls("is3370-1-c4", "Clause 4.3", "Limitation of Crack Width", "Design crack width for direct tension shall not exceed 0.2 mm for normal exposure and 0.1 mm for severe exposure.")]),

    ("is-3370-2-2009", "IS 3370 (Part 2):2009", "Concrete Structures for Storage of Liquids: Part 2 Reinforced Concrete Structures", 2009,
     "Civil & Construction", "Civil Engineering / CED 38", True, "Scheme I (ISI Mark)", "Water Retaining Structures Code",
     ["RCC water reservoir contractors", "overhead water tank builders"],
     "Mandatory structural calculation rules for bending moments, hoop tension, and minimum reinforcement in liquid tanks.",
     "Specifies minimum percentage of reinforcement to control thermal and shrinkage cracking.",
     ["hoop tension", "water tank reinforcement", "minimum reinforcement 0.35%", "liquid pressure design"],
     [cls("is3370-2-c7", "Clause 7.1", "Minimum Reinforcement in Walls & Floors", "Minimum reinforcement shall be 0.35% for high-strength deformed bars (TMT) in each orthogonal direction.")]),

    # Chemicals, Paints, Industrial Chemicals & Solvents
    ("is-101-1-1-1986", "IS 101 (Part 1/Sec 1):1986", "Methods of Sampling and Test for Paints, Varnishes: Sampling", 1986,
     "Chemical & Plastics", "Chemical / CHD 20", True, "Scheme I (ISI Mark)", "Paints Quality Testing Standards",
     ["paint quality control labs", "industrial coating inspection"],
     "Standard sampling methods for liquid paints, enamels, and varnishes from drums, cans, and bulk storage tanks.",
     "Prescribes sampling tools, composite sample preparation, and testing container seal integrity.",
     ["paint sampling", "sampling tube", "composite paint sample", "paint testing"],
     [cls("is101-1-1-c4", "Clause 4.1", "Sampling Protocol and Container Preparation", "Representative samples drawn using sampling thieves; sealed in clean airtight glass or tin containers.")]),

    ("is-101-5-1-1988", "IS 101 (Part 5/Sec 1):1988", "Methods of Sampling and Test for Paints: Mechanical Tests — Cross Cut Adhesion", 1988,
     "Chemical & Plastics", "Chemical / CHD 20", True, "Scheme I (ISI Mark)", "Paints Quality Testing Standards",
     ["paint manufacturing laboratories", "powder coating testing"],
     "Standard test procedure for cross-cut lattice pattern paint adhesion, evaluating resistance to flaking from metallic substrates.",
     "Covers multi-blade cutter grid test and pressure-sensitive tape adhesion rating from Class 0 to Class 5.",
     ["cross cut adhesion", "lattice pattern", "paint adhesion test", "tape peel test"],
     [cls("is101-5-1-c5", "Clause 5.1", "Cross Hatch Grid Adhesion Classification", "Lattice cut of 6x6 squares; tape applied and removed at 60° angle; edges of cuts completely smooth for Grade 0.")]),

    ("is-158-2005", "IS 158:2005", "Ready Mixed Paint, Brushing, Bituminous, Black, Lead-Free, Acid, Alkali and Heat Resisting", 2005,
     "Chemical & Plastics", "Chemical / CHD 20", True, "Scheme I (ISI Mark)", "Paints Quality Control Order",
     ["bituminous paint factories", "anticorrosive coating plants", "pipe coating units"],
     "Mandatory standard for acid, alkali, and water-resistant black bituminous protective coatings for underground pipelines and steel tanks.",
     "Covers drying time, flexibility (cold bend over 6mm mandrel), water immersion, and resistance to 5% sulfuric acid.",
     ["bituminous paint", "anti corrosive coating", "acid resistant paint", "pipeline coating", "lead free paint"],
     [cls("is158-c5", "Clause 5.1", "Acid and Alkali Chemical Resistance", "Painted steel panel immersed in 5% sulfuric acid and 5% sodium hydroxide for 48 hours without blistering or peeling.")]),

    ("is-5410-2013", "IS 5410:2013", "Cement Paint — Specification", 2013,
     "Chemical & Plastics", "Chemical / CHD 20", True, "Scheme I (ISI Mark)", "Paints Quality Control Order",
     ["cement paint plants", "powder coating factories"],
     "Mandatory specification for Portland cement-based dry powder exterior wall paints containing waterproofing additives.",
     "Covers white and colored cement paints, water repellency, opacity, and weather durability on masonry surfaces.",
     ["cement paint", "powder paint", "water repellency", "portland cement base", "masonry finish"],
     [cls("is5410-c6", "Clause 6.1", "Water Permeability and Resistance", "Painted test slab shall not allow water penetration exceeding 0.5 ml after 24 hours under 100mm head of water.")]),

    ("is-2932-2003", "IS 2932:2003", "Enamel, Synthetic, Exterior: (a) Undercoating, (b) Finishing — Specification", 2003,
     "Chemical & Plastics", "Chemical / CHD 20", True, "Scheme I (ISI Mark)", "Paints Quality Control Order",
     ["synthetic enamel manufacturing", "alkyd resin paint factories"],
     "Mandatory standard for high-gloss alkyd exterior synthetic enamel paint for metal and wood structures.",
     "Covers specular gloss (minimum 80% at 60°), scratch resistance (1500 g load), and accelerated weathering.",
     ["synthetic enamel", "alkyd paint", "specular gloss 80%", "scratch hardness 1500g", "lead limit <= 90ppm"],
     [cls("is2932-c5", "Clause 5.1", "Gloss, Scratch Hardness & Lead Prohibition", "Gloss at 60° >= 80 units; scratch test >= 1500g without bare metal breakthrough; lead content <= 90 ppm.")]),

    ("is-133-2004", "IS 133:2004", "Enamel, Interior: (a) Undercoating, (b) Finishing — Specification", 2004,
     "Chemical & Plastics", "Chemical / CHD 20", True, "Scheme I (ISI Mark)", "Paints Quality Control Order",
     ["interior paint plants", "wood enamel paint manufacturing"],
     "Mandatory standard for interior synthetic glossy enamel, regulating lead restriction (<90 ppm) and hard drying times.",
     "Covers indoor metal and wood coatings, covering power, and color stability.",
     ["interior enamel", "drying time", "surface dry 3h", "lead restriction 90ppm", "viscosity Ford cup"],
     [cls("is133-c5", "Clause 5.2", "Drying Time & Lead Content Threshold", "Surface dry in <= 3 hours, hard dry in <= 18 hours; heavy metals (lead, cadmium, chromium) restricted under E-Waste / QCO.")]),

    ("is-252-2013", "IS 252:2013", "Caustic Soda (Pure and Technical) — Specification", 2013,
     "Chemical & Plastics", "Chemical / CHD 1", True, "Scheme I (ISI Mark)", "Caustic Soda Quality Control Order",
     ["chlor-alkali chemical plants", "caustic soda flaking units", "membrane cell plants"],
     "Mandatory standard for Sodium Hydroxide (NaOH) in solid, lye, flakes, and block forms for soap, textile, and alumina refineries.",
     "Specifies purity (minimum 99.5% for pure, 96.0% for technical), carbonate limits, and chloride traces.",
     ["caustic soda", "sodium hydroxide", "NaOH 99.5%", "chlor-alkali", "caustic lye"],
     [cls("is252-c4", "Clause 4.1", "Assay Purity and Impurity Limits", "Technical grade NaOH >= 96.0% by mass; total carbonate (as Na2CO3) <= 1.5%; chlorides (as NaCl) <= 0.3%.")]),

    ("is-265-2021", "IS 265:2021", "Hydrochloric Acid — Specification", 2021,
     "Chemical & Plastics", "Chemical / CHD 1", True, "Scheme I (ISI Mark)", "Acids Quality Control Order",
     ["chemical synthesis plants", "steel pickling acid suppliers"],
     "Mandatory standard for technical and pure grades of Hydrochloric Acid (HCl), total acidity (minimum 30% by mass), and iron traces.",
     "Covers concentrated aqueous solutions of hydrogen chloride for industrial processing and metallurgy.",
     ["hydrochloric acid", "HCl 30%", "acid pickling", "iron content in acid", "specific gravity 1.15"],
     [cls("is265-c4", "Clause 4.1", "Total Acidity & Heavy Metals", "Specific gravity at 20°C >= 1.152; total acidity as HCl >= 30.0% by mass; iron (Fe) <= 0.005% for pure grade.")]),

    ("is-266-1993", "IS 266:1993", "Sulfuric Acid — Specification", 1993,
     "Chemical & Plastics", "Chemical / CHD 1", True, "Scheme I (ISI Mark)", "Acids Quality Control Order",
     ["sulfuric acid manufacturing", "fertilizer acid plants", "battery acid refiners"],
     "Mandatory standard for commercial, battery, and technical grades of Sulfuric Acid (H2SO4, 98% and oleum).",
     "Specifies concentration (minimum 98.0% for commercial), lead, arsenic, and residue on ignition.",
     ["sulfuric acid", "H2SO4 98%", "battery grade acid", "oleum", "acid manufacturing"],
     [cls("is266-c4", "Clause 4.1", "Concentration and Battery Grade Limits", "Commercial grade H2SO4 >= 98.0%; battery grade H2SO4 >= 98.0% with iron <= 0.005%, arsenic <= 0.0002%.")]),

    ("is-285-1992", "IS 285:1992", "Laundry Soaps — Specification", 1992,
     "Chemical & Plastics", "Chemical / CHD 25", True, "Scheme I (ISI Mark)", "Soaps Quality Control Order",
     ["soap factories", "detergent cake manufacturers"],
     "Mandatory standard for bar and cake laundry soaps, establishing Total Fatty Matter (TFM) grades (Type I: 62% TFM, Type II: 45% TFM).",
     "Covers saponified fatty matter, free caustic alkali limits, and rosin content in laundry soaps.",
     ["laundry soap", "TFM 62%", "total fatty matter", "free caustic alkali <= 0.2%", "washing soap"],
     [cls("is285-c5", "Clause 5.1", "Total Fatty Matter (TFM) & Rosin Content", "Type I pure soap TFM >= 62.0% by mass; free caustic alkali <= 0.2% as NaOH; matter insoluble in alcohol <= 3.0%.")]),

    ("is-2888-2004", "IS 2888:2004", "Toilet Soap — Specification", 2004,
     "Chemical & Plastics", "Chemical / CHD 25", True, "Scheme I (ISI Mark)", "Toilet Soaps Quality Control Order",
     ["toilet soap manufacturers", "personal care cosmetics factories"],
     "Mandatory standard classifying bath and toilet soaps into Grade 1 (76% TFM), Grade 2 (70% TFM), and Grade 3 (60% TFM).",
     "Specifies lather volume (minimum 200 ml), skin dermatological safety, and moisture limits.",
     ["toilet soap", "bath soap", "Grade 1 TFM 76%", "lather volume 200ml", "free alkali <= 0.05%"],
     [cls("is2888-c5", "Clause 5.1", "TFM Grading & Lather Volume Test", "Grade 1 TFM >= 76.0%; Grade 2 TFM >= 70.0%; Grade 3 TFM >= 60.0%; lather volume in standard cylinder >= 200 ml.")]),

    ("is-4955-2001", "IS 4955:2001", "Household Laundry Detergent Powders — Specification", 2001,
     "Chemical & Plastics", "Chemical / CHD 25", True, "Scheme I (ISI Mark)", "Detergents Quality Standards",
     ["detergent manufacturing plants", "spray dried detergent powder units"],
     "Mandatory standard for active matter content, cleaning efficiency, and phosphate biodegradability in laundry detergent powders.",
     "Covers Grade 1 (high efficiency), Grade 2, and Grade 3 household washing powders.",
     ["detergent powder", "active detergent matter >= 19%", "cleaning efficiency", "washing powder"],
     [cls("is4955-c5", "Clause 5.1", "Active Matter and Cleaning Performance", "Grade 1 active detergent matter >= 19.0% by mass; moisture <= 13.0%; cleaning efficiency index >= 100.")]),

    ("is-54-1988", "IS 54:1988", "Paraffin Wax — Specification", 1988,
     "Chemical & Plastics", "Chemical / CHD 18", True, "Scheme I (ISI Mark)", "Petroleum Products Standards",
     ["candle manufacturing", "wax coating converters", "petroleum refineries"],
     "Specifies melting point grades (Type 1 to Type 3, 50°C to 65°C), oil content, and color for fully refined paraffin wax.",
     "Covers refined waxes for food packaging wrappers, cosmetics, electrical insulation, and candle production.",
     ["paraffin wax", "melting point", "oil content <= 0.5%", "candle wax", "wax coating"],
     [cls("is54-c4", "Clause 4.1", "Melting Point and Oil Content", "Melting point (cooling curve) 50°C to 65°C; maximum oil content <= 0.5% by mass for fully refined wax.")]),

    ("is-1065-1989", "IS 1065:1989", "Bleaching Powder, Stable — Specification", 1989,
     "Chemical & Plastics", "Chemical / CHD 1", True, "Scheme I (ISI Mark)", "Chemicals Quality Standards",
     ["disinfectant manufacturing", "chlorinated lime chemical units"],
     "Specifies available chlorine (minimum 34.0% by mass), stability to heat, and moisture limits for chlorinated lime disinfectant powder.",
     "Covers municipal drinking water chlorination and surface sanitation chemical compounds.",
     ["bleaching powder", "available chlorine >= 34%", "water chlorination", "calcium hypochlorite"],
     [cls("is1065-c4", "Clause 4.1", "Available Chlorine & Heat Stability", "Available chlorine >= 34.0% by mass; loss of chlorine on heating at 100°C for 2 hours shall not exceed 1.5%.")]),

    ("is-544-2019", "IS 544:2019", "Carbon Disulfide, Technical — Specification", 2019,
     "Chemical & Plastics", "Chemical / CHD 1", True, "Scheme I (ISI Mark)", "Chemicals Quality Standards",
     ["viscose rayon manufacturing", "rubber vulcanization chemical plants"],
     "Specifies distillation range, non-volatile residue, and sulfur content for technical grade Carbon Disulfide (CS2).",
     "Covers raw materials for cellophane, carbon tetrachloride synthesis, and viscose staple fiber production.",
     ["carbon disulfide", "CS2", "viscose rayon", "distillation range", "chemical solvent"],
     [cls("is544-c4", "Clause 4.1", "Distillation Range & Purity", "Distillation range: 100% distill between 46.0°C and 47.0°C at 760 mm Hg; non-volatile residue <= 0.005%.")]),

    ("is-170-2020", "IS 170:2020", "Acetone — Specification", 2020,
     "Chemical & Plastics", "Chemical / CHD 1", True, "Scheme I (ISI Mark)", "Solvents Quality Control Order",
     ["chemical synthesis plants", "pharmaceutical solvent recovery units", "paint thinner plants"],
     "Mandatory standard for pure Acetone solvent (dimethyl ketone), purity (minimum 99.5% by GC), and water content limits.",
     "Covers industrial grade and laboratory grade acetone for acrylic resins, pharmaceuticals, and paints.",
     ["acetone", "solvent purity 99.5%", "dimethyl ketone", "moisture in acetone <= 0.3%", "gas chromatography"],
     [cls("is170-c4", "Clause 4.1", "Purity and Distillation Range", "Purity by GC >= 99.5% by mass; distillation range 55.6°C to 56.6°C; permanganate fading time >= 120 minutes.")])
]
