# Batch 2: Electrotechnical, Electronics, IT Hardware & Renewable Energy (65 Standards)
# Total after Batch 2 = 60 + 65 + 65 = 190 standards

def cls(cid, num, title, content, test_req=None, mandatory=True):
    c = {
        "id": cid,
        "number": num,
        "title": title,
        "content": content,
        "mandatory": mandatory
    }
    if test_req:
        c["testRequirement"] = test_req
        c["testMethod"] = test_req
    return c

BATCH_2_DATA = [
    # Wiring & Earthing
    ("is-732-2019", "IS 732:2019", "Code of Practice for Electrical Wiring Installations", 2019,
     "Electrical", "Electrotechnical / ETD 20", True, "Scheme I (ISI Mark)", "National Electrical Code",
     ["electrical contractors", "building wiring engineers", "switchboard panel builders"],
     "National safety code for building electrical installations, wire sizing, conduit routing, and circuit breaker protection.",
     "Covers design, erection, testing, and commissioning of electrical wiring up to 1000 V AC.",
     ["electrical wiring", "cable sizing", "conduit wiring", "circuit breaker", "insulation resistance 1Mohm"],
     [cls("is732-c5", "Clause 5.1", "Insulation Resistance Verification", "Insulation resistance between conductors and earth shall be measured at 500V DC and exceed 1.0 Megaohm.")]),

    ("is-3043-2018", "IS 3043:2018", "Code of Practice for Earthing — Specification", 2018,
     "Electrical", "Electrotechnical / ETD 20", True, "Scheme I (ISI Mark)", "National Electrical Code",
     ["earthing electrode manufacturers", "substation engineers", "industrial lightning protection"],
     "Mandatory engineering code for system earthing, equipment grounding, earth pit resistance, and copper/GI plate electrodes.",
     "Covers calculation of earth fault currents, touch and step potentials, and chemical earthing compounds.",
     ["earthing", "earth pit", "grounding electrode", "earth resistance <= 1 ohm", "touch potential", "step potential"],
     [cls("is3043-c7", "Clause 7.2", "Earth Electrode Resistance Limits", "Earth resistance of electrical substation grid <= 1.0 Ohm; commercial building system earth <= 2.0 Ohm.")]),

    # Power Transformers & Transmission
    ("is-2026-1-2011", "IS 2026 (Part 1):2011", "Power Transformers — Part 1: General Requirements", 2011,
     "Electrical", "Electrotechnical / ETD 16", True, "Scheme I (ISI Mark)", "Transformers Quality Control Order",
     ["power transformer plants", "electrical grid manufacturing", "substation transformers"],
     "Mandatory standard for ratings, winding taps, connection symbols, and general tolerances for power transformers.",
     "Applies to three-phase and single-phase power transformers of all power ratings.",
     ["power transformer", "vector group Dyn11", "no load loss", "load loss", "impedance voltage"],
     [cls("is2026-1-c6", "Clause 6.1", "Losses and Impedance Tolerances", "No-load loss tolerance +15%; total loss tolerance +10%; component impedance within ±10% of declared rating.")]),

    ("is-2026-2-2010", "IS 2026 (Part 2):2010", "Power Transformers — Part 2: Temperature Rise", 2010,
     "Electrical", "Electrotechnical / ETD 16", True, "Scheme I (ISI Mark)", "Transformers Quality Control Order",
     ["transformer testing labs", "cooling system manufacturers"],
     "Mandatory limits on oil temperature rise (50°C/55°C) and winding temperature rise (55°C/60°C) above 50°C ambient.",
     "Prescribes heat run test and cooling methods: ONAN, ONAF, OFAF, ODAF.",
     ["temperature rise test", "heat run test", "oil temperature 50C", "winding rise 55C", "ONAN cooling"],
     [cls("is2026-2-c4", "Clause 4.1", "Maximum Permissible Temperature Rise", "Top oil temperature rise shall not exceed 50°C; average winding temperature rise by resistance method <= 55°C.")]),

    ("is-2026-3-2009", "IS 2026 (Part 3):2009", "Power Transformers — Part 3: Insulation Levels and Dielectric Tests", 2009,
     "Electrical", "Electrotechnical / ETD 16", True, "Scheme I (ISI Mark)", "Transformers Quality Control Order",
     ["high voltage test bays", "transformer manufacturing plants"],
     "Prescribes Lightning Impulse (BIL) tests, switching impulse, and power frequency separate source withstand voltage tests.",
     "Covers insulation coordination and dielectric withstand criteria for high voltage power transformers.",
     ["dielectric test", "lightning impulse test BIL", "power frequency withstand", "partial discharge test"],
     [cls("is2026-3-c7", "Clause 7.3", "Lightning Impulse Full Wave Test", "Windings subjected to 1.2/50 microsecond full lightning impulse wave without breakdown or wave deformation.")]),

    ("is-2026-5-2011", "IS 2026 (Part 5):2011", "Power Transformers — Part 5: Ability to Withstand Short Circuit", 2011,
     "Electrical", "Electrotechnical / ETD 16", True, "Scheme I (ISI Mark)", "Transformers Quality Control Order",
     ["CPRI high power testing labs", "grid transformer design engineers"],
     "Mandatory requirements for thermal and dynamic electrodynamic stress withstand during external short circuits.",
     "Covers short circuit duration (2.0 seconds) and peak dynamic electromagnetic forces.",
     ["short circuit withstand", "dynamic force withstand", "thermal short circuit 2s", "CPRI test"],
     [cls("is2026-5-c4", "Clause 4.1", "Dynamic Short Circuit Proof Test", "Transformer shall withstand 9 full asymmetrical short-circuit current impulses without structural winding displacement.")]),

    ("is-11171-1985", "IS 11171:1985", "Dry-Type Power Transformers — Specification", 1985,
     "Electrical", "Electrotechnical / ETD 16", True, "Scheme I (ISI Mark)", "Transformers Quality Control Order",
     ["cast resin transformer factories", "indoor substation builders", "metro rail power supply"],
     "Mandatory standard for cast resin and vacuum pressure impregnated (VPI) dry-type fire-safe indoor transformers.",
     "Covers Class F and Class H insulation, environmental class, and fire behavior test.",
     ["dry type transformer", "cast resin", "VPI transformer", "Class F insulation", "fire safe transformer"],
     [cls("is11171-c7", "Clause 7.1", "Insulation Class & Temperature Rise", "Class F winding temperature rise <= 90°C; Class H temperature rise <= 115°C above 40°C ambient.")]),

    ("is-2099-1986", "IS 2099:1986", "Bushings for Alternating Voltages Above 1000 V — Specification", 1986,
     "Electrical", "Electrotechnical / ETD 19", True, "Scheme I (ISI Mark)", "Electrical Bushings Standards",
     ["high voltage bushing manufacturers", "porcelain and RIP bushing plants"],
     "Specifies electrical and mechanical requirements for outdoor oil-impregnated paper (OIP) and resin-impregnated paper (RIP) bushings.",
     "Covers creeping distance, power factor (tan delta), and cantilever mechanical load.",
     ["HV bushing", "OIP bushing", "RIP bushing", "tan delta <= 0.005", "cantilever load"],
     [cls("is2099-c8", "Clause 8.1", "Dielectric Dissipation Factor (Tan Delta)", "Dielectric dissipation factor tan delta at ambient temperature shall not exceed 0.005 (0.5%) at rated voltage.")]),

    ("is-2544-1973", "IS 2544:1973", "Porcelain Post Insulators for Systems with Nominal Voltages Greater Than 1000 V", 1973,
     "Electrical", "Electrotechnical / ETD 6", True, "Scheme I (ISI Mark)", "Insulators Quality Control Order",
     ["substation insulator factories", "porcelain ceramic units"],
     "Mandatory standard for solid core post insulators used in high voltage outdoor substations (11 kV to 400 kV).",
     "Specifies mechanical bending strength, torsion withstand, puncture test, and artificial pollution test.",
     ["post insulator", "substation insulator", "bending strength", "porcelain post", "creepage distance"],
     [cls("is2544-c7", "Clause 7.1", "Cantilever Failing Load Test", "Insulator shall withstand specified mechanical cantilever failing load (up to 12 kN) without fracture of porcelain or cement.")]),

    ("is-731-1971", "IS 731:1971", "Porcelain Insulators for Overhead Power Lines with a Nominal Voltage Greater Than 1000 V", 1971,
     "Electrical", "Electrotechnical / ETD 6", True, "Scheme I (ISI Mark)", "Insulators Quality Control Order",
     ["transmission line insulator factories", "disc insulator plants"],
     "Mandatory standard for disc suspension and pin insulators used on overhead electric transmission and distribution towers.",
     "Covers electromechanical failing load (70 kN to 210 kN), impulse puncture withstand, and thermal shock cycles.",
     ["disc insulator", "suspension insulator", "electromechanical failing load 70kN", "puncture test", "thermal shock"],
     [cls("is731-c8", "Clause 8.2", "Electromechanical Failing Load Test", "Insulators subjected simultaneously to mechanical tensile load and 75% power frequency voltage without mechanical or electrical failure.")]),

    # Fuses & Switchgear
    ("is-13703-1-1993", "IS 13703 (Part 1):1993", "Low-Voltage Fuses — Part 1: General Requirements (HRC Fuses)", 1993,
     "Electrical", "Electrotechnical / ETD 39", True, "Scheme I (ISI Mark)", "Low Voltage Switchgear Standards",
     ["HRC fuse manufacturers", "electrical fuse link plants"],
     "Mandatory standard for High Rupturing Capacity (HRC) low-voltage cartridge fuses up to 1000 V AC and 100 kA breaking capacity.",
     "Covers time-current characteristics, cut-off current, and Joule integral (I²t) energy let-through.",
     ["HRC fuse", "cartridge fuse", "breaking capacity 100kA", "I2t let through", "fuse link"],
     [cls("is13703-1-c8", "Clause 8.1", "Breaking Capacity Test (100 kA)", "Fuses must safely interrupt short circuit current of 100 kA at 1.1 times rated voltage without explosive fragmentation.")]),

    ("is-13703-2-1993", "IS 13703 (Part 2):1993", "Low-Voltage Fuses: Part 2 Fuses for Use by Authorized Persons (Industrial Fuses)", 1993,
     "Electrical", "Electrotechnical / ETD 39", True, "Scheme I (ISI Mark)", "Low Voltage Switchgear Standards",
     ["industrial fuse plants", "knife contact blade factories"],
     "Specifies dimensional interchangeability, slotted tags, and knife-blade contacts for industrial bolted and blade fuse links.",
     "Covers DIN and BS type industrial fuse configurations for motor feeder protection.",
     ["industrial fuse", "bolted fuse", "knife blade fuse", "DIN type fuse", "power dissipation"],
     [cls("is13703-2-c5", "Clause 5.1", "Power Dissipation Limits", "Power dissipation in watts at rated current shall not exceed threshold values specified in Table 1 to prevent overheating.")]),

    ("is-13947-1-1993", "IS 13947 (Part 1):1993", "Low-Voltage Switchgear and Controlgear — Part 1: General Rules", 1993,
     "Electrical", "Electrotechnical / ETD 39", True, "Scheme I (ISI Mark)", "LV Switchgear Quality Control Order",
     ["switchgear manufacturing plants", "control panel assemblers"],
     "Foundational standard defining utilization categories (AC-1 to AC-4), IP degree of ingress protection, and clearances.",
     "Applies to low-voltage electrical circuit control, switching, and protection equipment up to 1000 V AC.",
     ["switchgear", "utilization category AC-3", "IP55 ingress", "creepage distance", "impulse withstand Uimp"],
     [cls("is13947-1-c7", "Clause 7.1", "Dielectric Properties & Clearances", "Clearances and creepage distances shall withstand rated impulse voltage Uimp (up to 8 kV) per Table 12.")]),

    ("is-13947-2-1993", "IS 13947 (Part 2):1993", "Low-Voltage Switchgear and Controlgear: Part 2 Circuit-Breakers (MCCB & ACB)", 1993,
     "Electrical", "Electrotechnical / ETD 39", True, "Scheme I (ISI Mark)", "Circuit Breakers Quality Control Order",
     ["MCCB manufacturing plants", "Air Circuit Breaker (ACB) factories"],
     "Mandatory standard for Moulded Case Circuit Breakers (MCCB) and Air Circuit Breakers (ACB), Icu and Ics short-circuit capacities.",
     "Covers thermal-magnetic and electronic trip releases, service breaking capacity (Ics = 100% Icu).",
     ["MCCB", "ACB", "circuit breaker", "Icu breaking capacity 50kA", "Ics service capacity", "thermal overload"],
     [cls("is13947-2-c8", "Clause 8.3", "Rated Service Short-Circuit Breaking Capacity (Ics)", "Circuit breaker must clear sequence O - t - CO - t - CO at rated Ics and remain functional with full dielectric integrity.")]),

    ("is-13947-3-1993", "IS 13947 (Part 3):1993", "Switches, Disconnectors, Switch-Disconnectors and Fuse-Combination Units", 1993,
     "Electrical", "Electrotechnical / ETD 39", True, "Scheme I (ISI Mark)", "LV Switchgear Quality Control Order",
     ["isolator manufacturing", "fuse switch unit factories", "on-load changeover switch plants"],
     "Mandatory standard for on-load rotary isolators, changeover switches, and switch-disconnector-fuse (SDF) units.",
     "Covers making and breaking capacity under inductive motor loads (AC-23A) and operational durability.",
     ["isolator", "changeover switch", "SDF unit", "switch disconnector", "AC-23A inductive switching"],
     [cls("is13947-3-c7", "Clause 7.2", "Making and Breaking Capacities (AC-23A)", "Switch must make 10 times rated current and break 8 times rated current at 1.05 times voltage and 0.35 power factor.")]),

    ("is-13947-4-1-1993", "IS 13947 (Part 4/Sec 1):1993", "Contactors and Motor-Starters: Electromechanical Contactors", 1993,
     "Electrical", "Electrotechnical / ETD 39", True, "Scheme I (ISI Mark)", "Motor Starters Standards",
     ["contactor manufacturers", "DOL and star-delta starter plants"],
     "Mandatory standard for AC power contactors (9A to 800A), bimetallic thermal overload relays, and motor starters.",
     "Covers mechanical endurance (10 million operations), electrical endurance under AC-3 duty, and coil pick-up voltage.",
     ["power contactor", "motor starter", "overload relay", "AC-3 duty", "electrical endurance 1 million"],
     [cls("is13947-4-c8", "Clause 8.2", "Electrical Operational Endurance", "Contactors must endure at least 1,000,000 electrical make-break operations under AC-3 motor starting condition without contact welding.")]),

    ("is-13947-5-1-2004", "IS 13947 (Part 5/Sec 1):2004", "Control Circuit Devices and Switching Elements — Electromechanical Control Devices", 2004,
     "Electrical", "Electrotechnical / ETD 39", True, "Scheme I (ISI Mark)", "Control Devices Standards",
     ["push button station factories", "limit switch manufacturing", "selector switch plants"],
     "Specifies mechanical and electrical durability of 22.5 mm push buttons, emergency stop actuators, and industrial limit switches.",
     "Covers IP65 ingress, positive opening operation of emergency stops, and pilot light LED indicators.",
     ["push button 22.5mm", "limit switch", "emergency stop", "pilot light", "positive opening contact"],
     [cls("is13947-5-c8", "Clause 8.1", "Emergency Stop Direct Opening Action", "Emergency stop actuators must feature direct drive positive opening operation (no intervening springs) per Annexure K.")]),

    # Energy Meters & Metering
    ("is-14697-1999", "IS 14697:1999", "AC Static Transformer Operated Watt-Hour and VAR-Hour Meters (Class 0.2S and 0.5S)", 1999,
     "Electrical", "Electrotechnical / ETD 13", True, "Scheme I (ISI Mark)", "Energy Meters Quality Control Order",
     ["grid tariff meter manufacturers", "HT electricity meter plants"],
     "Mandatory standard for high-accuracy substation grid meters and commercial HT boundary energy tariff meters.",
     "Covers Class 0.2S and 0.5S metrological accuracy, anti-tamper security, and DLMS protocol communication.",
     ["grid meter", "HT meter", "Class 0.2S", "transformer operated meter", "anti-tamper", "DLMS"],
     [cls("is14697-c6", "Clause 6.1", "High Accuracy Metrology (Class 0.2S)", "Measurement error shall remain strictly within ±0.2% over 5% to 120% rated current across 0.5 inductive to unity power factor.")]),

    ("is-13779-1999", "IS 13779:1999", "AC Static Watt-Hour Meters, Class 1 and 2 — Specification", 1999,
     "Electrical", "Electrotechnical / ETD 13", True, "Scheme I (ISI Mark)", "Energy Meters Quality Control Order",
     ["residential energy meter factories", "electronic kWh meter manufacturing"],
     "Mandatory standard for single-phase and three-phase direct connected residential static electricity meters.",
     "Covers electromagnetic immunity (EMC 10 V/m), starting current threshold (0.2% Ib), and voltage surge protection.",
     ["residential energy meter", "kWh meter", "Class 1.0", "anti tamper", "EMC immunity", "starting current"],
     [cls("is13779-c8", "Clause 8.1", "Starting Current and No-Load Creep", "Meter shall start and continuously record energy at 0.2% of basic current; under no load with 115% voltage, meter shall not register creep.")]),

    # Lighting & LED Systems
    ("is-15885-1-2011", "IS 15885 (Part 1):2011", "Lamp Controlgear — Part 1: General and Safety Requirements", 2011,
     "Electronics & IT", "Electrotechnical / ETD 23", True, "Compulsory Registration Scheme (CRS)", "Electronics Quality Control Order",
     ["electronic ballast factories", "LED driver plants", "lighting power supply units"],
     "Mandatory safety standard for electronic ballasts and power controlgear feeding fluorescent lamps, HID, and LED fixtures.",
     "Covers electrical insulation, creepage distances, thermal protection, and fire resistance.",
     ["lamp controlgear", "electronic ballast", "creepage distance", "thermal endurance", "CRS registration"],
     [cls("is15885-1-c8", "Clause 8.1", "Insulation Resistance & Electric Strength", "Insulation resistance >= 4 Megaohms; dielectric test with 2U + 1000 V AC applied for 1 minute without breakdown.")]),

    ("is-16103-1-2012", "IS 16103 (Part 1):2012", "LED Modules for General Lighting — Part 1: Safety Specifications", 2012,
     "Electronics & IT", "Electrotechnical / ETD 23", True, "Compulsory Registration Scheme (CRS)", "Electronics Quality Control Order",
     ["LED SMD PCB assembly", "LED light module plants"],
     "Mandatory CRS standard for self-ballasted and non-self-ballasted LED modules used in commercial and architectural fixtures.",
     "Covers eye safety, thermal management, creepage, and electric shock prevention.",
     ["LED module", "SMD LED", "LED safety", "creepage", "CRS registration", "thermal pad"],
     [cls("is16103-1-c7", "Clause 7.1", "Protection Against Electric Shock", "Accessible parts of non-isolated LED modules shall be protected against direct contact with live circuit traces.")]),

    ("is-16107-1-2012", "IS 16107 (Part 1):2012", "Luminaires — Part 1: General Requirements and Tests", 2012,
     "Electronics & IT", "Electrotechnical / ETD 23", True, "Scheme I (ISI Mark)", "Luminaires Standards",
     ["luminaire manufacturing factories", "commercial light fitting plants"],
     "General construction, internal wiring, mechanical impact resistance (IK rating), and thermal endurance of light fittings.",
     "Covers luminaires for use with tungsten filament, tubular fluorescent, and other discharge lamps.",
     ["luminaire", "light fixture", "IK impact rating", "thermal endurance test", "IP protection"],
     [cls("is16107-1-c9", "Clause 9.2", "Endurance Test & Thermal Investigation", "Luminaire operated in thermal draught-free enclosure for 240 hours continuously without thermal degradation of insulation.")]),

    ("is-16107-2-1-2012", "IS 16107 (Part 2/Sec 1):2012", "Luminaires: Part 2 Particular Requirements — Fixed General Purpose Luminaires", 2012,
     "Electronics & IT", "Electrotechnical / ETD 23", True, "Scheme I (ISI Mark)", "Luminaires Standards",
     ["recessed ceiling light factories", "surface mounted LED panel manufacturers"],
     "Specific requirements for fixed general purpose ceiling lights, downlights, and architectural troffers.",
     "Covers mechanical mounting stability, earthing continuity, and gland cord anchorage.",
     ["downlight", "ceiling light", "LED panel", "cord anchorage", "earthing continuity"],
     [cls("is16107-2-1-c5", "Clause 5.1", "Cord Anchorage Pull and Torsion Test", "Cord anchorage subjected to 25 cycles of 60 N axial pull without conductor displacement exceeding 2.0 mm.")]),

    ("is-16108-2012", "IS 16108:2012", "Photobiological Safety of Lamps and Lamp Systems", 2012,
     "Electronics & IT", "Electrotechnical / ETD 23", True, "Scheme I (ISI Mark)", "Lighting Eye Safety Order",
     ["LED optical testing laboratories", "spectroradiometer test facilities"],
     "Mandatory standard evaluating retinal blue-light hazard, UV actinic hazard, and thermal skin injury from high-power LEDs.",
     "Classifies lighting sources into Exempt Group (no hazard), Risk Group 1 (low), Risk Group 2 (moderate), and Risk Group 3 (high).",
     ["blue light hazard", "photobiological safety", "Risk Group 0 RG0", "retinal thermal hazard", "UV actinic"],
     [cls("is16108-c4", "Clause 4.3", "Retinal Blue Light Hazard Exposure Limit", "Blue light radiance weighted spectrum Lb shall not exceed 100 W/m²/sr for RG0 (Exempt Group) classification.")]),

    ("is-16106-2012", "IS 16106:2012", "Method of Electrical and Photometric Measurements of Solid-State Lighting (LED) Products", 2012,
     "Electronics & IT", "Electrotechnical / ETD 23", True, "Scheme I (ISI Mark)", "Lighting Testing Standards",
     ["integrating sphere test labs", "goniophotometer facilities"],
     "Standard test procedures for measuring total luminous flux (lumens), luminous efficacy (lm/W), CRI, and CCT using integrating spheres.",
     "Covers laboratory calibration protocols for all solid-state LED luminaires and lamps.",
     ["luminous flux", "lumens per watt", "integrating sphere", "CRI >= 80", "correlated color temperature CCT"],
     [cls("is16106-c6", "Clause 6.1", "Total Luminous Flux & Efficacy Measurement", "Luminous flux measured at (25 ± 1)°C stabilized operating temperature inside 2.0 meter integrating sphere spectrometer.")]),

    # Electric Motors & Domestic Appliances
    ("is-996-2009", "IS 996:2009", "Single-Phase AC Induction Motors for General Purpose — Specification", 2009,
     "Electrical", "Electrotechnical / ETD 15", True, "Scheme I (ISI Mark)", "Electric Motors Quality Control Order",
     ["single phase motor factories", "cooler motor manufacturing", "air blower motor plants"],
     "Mandatory standard for capacitor-start, capacitor-run, and split-phase fractional horsepower (FHP) motors up to 2.2 kW.",
     "Covers starting torque, full-load efficiency, temperature rise, and centrifugal switch endurance.",
     ["single phase motor", "cooler motor", "FHP motor", "capacitor start", "starting torque 200%"],
     [cls("is996-c7", "Clause 7.1", "Temperature Rise & Locked Rotor Torque", "Class B insulation temperature rise <= 80°C by resistance; locked rotor torque >= 200% of rated full-load torque.")]),

    ("is-12615-2018", "IS 12615:2018", "Line Operated Three-Phase Induction Motors (IE2, IE3, IE4 Efficiency Classes)", 2018,
     "Electrical", "Electrotechnical / ETD 15", True, "Scheme I (ISI Mark)", "Electric Motors Quality Control Order",
     ["three phase motor manufacturing", "IE3 motor plants", "industrial pump motor factories"],
     "Mandatory energy efficiency standard enforcing IE2 (High), IE3 (Premium), and IE4 (Super Premium) ratings for motors from 0.75 kW to 375 kW.",
     "Covers loss determination per IS 15999 (stray load losses, iron losses, rotor I²R losses).",
     ["three phase motor", "IE3 efficiency", "energy efficient motor", "stray load loss", "BEE star rating"],
     [cls("is12615-c6", "Clause 6.1", "Minimum Energy Efficiency Values (IE3)", "For 4-pole 7.5 kW motor: minimum nominal full load efficiency shall not be less than 90.4% per Table 3.")]),

    ("is-325-1996", "IS 325:1996", "Three-Phase Induction Motors — Specification", 1996,
     "Electrical", "Electrotechnical / ETD 15", True, "Scheme I (ISI Mark)", "Electric Motors Quality Control Order",
     ["electric motor manufacturing", "submersible motor plants"],
     "Foundational standard for mechanical dimensions, terminal markings, mounting types (B3 foot, B5 flange), and vibration limits.",
     "Covers general industrial squirrel cage and slip ring three-phase induction motors.",
     ["induction motor", "squirrel cage", "B3 mounting", "vibration velocity <= 1.8 mm/s", "terminal marking"],
     [cls("is325-c9", "Clause 9.1", "Vibration and Overload Withstand", "Vibration velocity shall not exceed 1.8 mm/s RMS; motor shall withstand 1.6 times rated torque for 15 seconds without stalling.")]),

    ("is-900-1992", "IS 900:1992", "Code of Practice for Installation and Maintenance of Induction Motors", 1992,
     "Electrical", "Electrotechnical / ETD 15", False, "Scheme I (ISI Mark)", "National Electrical Code",
     ["industrial maintenance engineers", "motor rewinding workshops"],
     "Engineering code of practice for motor foundation alignment, belt tensioning, bearing lubrication, and insulation testing.",
     "Covers preventative maintenance schedule and failure diagnostics for industrial electric motors.",
     ["motor installation", "shaft alignment", "bearing grease", "megger test", "preventative maintenance"],
     [cls("is900-c5", "Clause 5.2", "Shaft Dial Indicator Alignment", "Angular and parallel shaft misalignment measured by dial indicator shall not exceed 0.05 mm.")]),

    ("is-14155-1994", "IS 14155:1994", "Domestic Electric Food Mixers (Mixer-Grinders) — Specification", 1994,
     "Electrical", "Electrotechnical / ETD 32", True, "Scheme I (ISI Mark)", "Household Appliances Quality Order",
     ["mixer grinder factories", "food processor manufacturing"],
     "Mandatory standard for kitchen mixer grinders, motor thermal overload protectors, jar interlocking, and blade retention.",
     "Covers electrical safety, motor temperature rise under turmeric load, and noise levels.",
     ["mixer grinder", "food processor", "thermal overload protector TOP", "turmeric grinding test", "jar lock"],
     [cls("is14155-c7", "Clause 7.1", "Grinding Performance & Motor Protection", "Must grind 50g dry turmeric fingers to 300 micron mesh within 2 minutes; TOP must trip before motor winding exceeds 130°C.")]),

    ("is-302-2-30-2007", "IS 302 (Part 2/Sec 30):2007", "Safety of Household Electrical Appliances: Particular Requirements for Room Heaters", 2007,
     "Electrical", "Electrotechnical / ETD 32", True, "Scheme I (ISI Mark)", "Household Appliances Quality Order",
     ["room heater factories", "oil filled radiator plants", "halogen heater manufacturing"],
     "Mandatory safety standard for electric room heaters, convection radiators, fan heaters, and quartz radiant heaters.",
     "Covers tip-over safety switches, surface temperature limits, and fire hazard prevention.",
     ["room heater", "oil filled radiator", "fan heater", "tip over switch", "fire hazard test"],
     [cls("is302-2-30-c19", "Clause 19.11", "Tilt / Tip-Over Cut-Off Mechanism", "Heater tilted at 15° in any direction must automatically cut off power supply within 1.0 second.")]),

    ("is-302-2-35-2017", "IS 302 (Part 2/Sec 35):2017", "Safety of Household Electrical Appliances: Electric Instantaneous Water Heaters", 2017,
     "Electrical", "Electrotechnical / ETD 32", True, "Scheme I (ISI Mark)", "Water Heaters Quality Control Order",
     ["instant geyser factories", "gas/electric water heater plants"],
     "Mandatory safety standard for instantaneous geysers (tankless), pressure release valves, and dry-heating cutoffs.",
     "Covers high water pressure proof test (up to 1.0 MPa), earth leakage, and boiling prevention thermostats.",
     ["instant geyser", "water heater", "pressure relief valve 1.0MPa", "thermal cut out", "dry burn test"],
     [cls("is302-2-35-c22", "Clause 22.1", "Hydrostatic Pressure Withstand", "Water container shall withstand 1.5 times maximum rated operating pressure (minimum 1.0 MPa) without rupture or deformation.")]),

    ("is-302-2-15-2009", "IS 302 (Part 2/Sec 15):2009", "Safety of Household Electrical Appliances: Particular Requirements for Heating Liquids", 2009,
     "Electrical", "Electrotechnical / ETD 32", True, "Scheme I (ISI Mark)", "Household Appliances Quality Order",
     ["electric kettle manufacturing", "coffee maker factories", "egg boiler plants"],
     "Mandatory safety standard for electric kettles, coffee makers, and liquid heaters.",
     "Covers automatic steam switch shutoff, boil-dry thermal protection, and cordless connector contact endurance.",
     ["electric kettle", "boil dry protection", "steam switch", "cordless base", "strix connector"],
     [cls("is302-2-15-c19", "Clause 19.101", "Boil-Dry Thermal Switch Action", "Kettle operated without water; thermal cut-out must disconnect circuit before base temperature exceeds 260°C.")]),

    ("is-302-2-24-1994", "IS 302 (Part 2/Sec 24):1994", "Safety of Household Electrical Appliances: Refrigerating Appliances", 1994,
     "Electrical", "Electrotechnical / ETD 32", True, "Scheme I (ISI Mark)", "Refrigerators Quality Control Order",
     ["domestic refrigerator plants", "deep freezer factories"],
     "Mandatory electrical and mechanical safety standard for domestic frost-free and direct cool refrigerators.",
     "Covers flammable refrigerant safety (R600a isobutane), compressor earthing, defroster heater insulation, and condensation drain.",
     ["refrigerator safety", "R600a isobutane", "compressor earth", "defrost heater", "door gasket seal"],
     [cls("is302-2-24-c22", "Clause 22.101", "Flammable Refrigerant Leakage Protection", "In the event of R600a circuit rupture, refrigerant concentration inside food compartment shall not exceed 75% of lower flammability limit.")]),

    ("is-302-2-23-2009", "IS 302 (Part 2/Sec 23):2009", "Safety of Household Electrical Appliances: Appliances for Skin or Hair Care", 2009,
     "Electrical", "Electrotechnical / ETD 32", True, "Scheme I (ISI Mark)", "Personal Care Appliances Order",
     ["hair dryer manufacturing", "hair straightener factories"],
     "Mandatory safety standard for hair dryers, curling irons, hair straighteners, and facial steamers.",
     "Covers thermal cutouts, air inlet blockage test, cord flexure endurance, and high voltage dielectric strength.",
     ["hair dryer", "hair straightener", "blocked air inlet test", "cord flexure 20000 cycles", "thermal fuse"],
     [cls("is302-2-23-c19", "Clause 19.101", "Air Intake Obstruction Test", "Hair dryer air inlet completely blocked with paper; thermal limiter must safely isolate heating coil without casing ignition.")]),

    ("is-302-2-80-2017", "IS 302 (Part 2/Sec 80):2017", "Safety of Household Electrical Appliances: Particular Requirements for Electric Fans", 2017,
     "Electrical", "Electrotechnical / ETD 32", True, "Scheme I (ISI Mark)", "Electric Fans Quality Order",
     ["ceiling fan factories", "pedestal and exhaust fan plants"],
     "Mandatory safety standard for ceiling fans, exhaust fans, pedestal fans, and wall bracket fans.",
     "Covers suspension shackle secondary safety wire rope, blade finger guard probe tests, and moisture resistance.",
     ["ceiling fan", "safety wire rope", "blade guard finger probe", "suspension shackle", "BEE star rating"],
     [cls("is302-2-80-c20", "Clause 20.2", "Finger Guard Enclosure Probe Test", "Test probe B of IS 1401 applied with 20 N force shall not touch rotating fan blades through protective guard mesh.")]),

    ("is-302-2-7-2010", "IS 302 (Part 2/Sec 7):2010", "Safety of Household Electrical Appliances: Washing Machines", 2010,
     "Electrical", "Electrotechnical / ETD 32", True, "Scheme I (ISI Mark)", "Washing Machines Quality Order",
     ["washing machine manufacturing", "front load and top load plants"],
     "Mandatory safety standard for semi-automatic and fully-automatic front/top load domestic clothes washing machines.",
     "Covers spin tub brake interlock (<12 seconds stop time), water overflow protection, and dynamic unbalance vibration.",
     ["washing machine", "spin tub brake <= 12s", "water overflow test", "lid safety interlock", "spin drum balance"],
     [cls("is302-2-7-c20", "Clause 20.101", "Spin Tub Lid Interlock Braking", "Opening spin basket lid during 1000 RPM high-speed spin cycle must brake drum to complete stop within 12 seconds.")]),

    ("is-302-2-25-2014", "IS 302 (Part 2/Sec 25):2014", "Safety of Household Electrical Appliances: Microwave Ovens", 2014,
     "Electrical", "Electrotechnical / ETD 32", True, "Scheme I (ISI Mark)", "Microwave Ovens Quality Order",
     ["microwave oven manufacturing plants", "combination microwave factories"],
     "Mandatory standard for domestic and commercial microwave ovens, regulating microwave radiation leakage (<50 W/m²).",
     "Covers door interlock switches (dual safety monitors), cavity fire containment, and high voltage magnetron safety.",
     ["microwave oven", "radiation leakage <= 5mW/cm²", "dual door interlock", "magnetron", "cavity fire test"],
     [cls("is302-2-25-c32", "Clause 32.1", "Microwave Radiation Leakage Limit", "Microwave power leakage measured at 50 mm distance from any external surface shall not exceed 50 W/m² (5 mW/cm²).")]),

    ("is-302-2-2-2018", "IS 302 (Part 2/Sec 2):2018", "Safety of Household Electrical Appliances: Vacuum Cleaners", 2018,
     "Electrical", "Electrotechnical / ETD 32", True, "Scheme I (ISI Mark)", "Household Appliances Quality Order",
     ["vacuum cleaner manufacturing", "robotic vacuum cleaner assembly"],
     "Mandatory standard for canister, upright, and wet-and-dry domestic vacuum cleaners.",
     "Covers motor cooling airflow, water ingestion safety, current-carrying suction hose endurance, and radio interference.",
     ["vacuum cleaner", "suction hose flexure", "wet pickup safety", "motor overheating", "double insulation"],
     [cls("is302-2-2-c21", "Clause 21.101", "Current-Carrying Hose Flexure Test", "Electrified suction hose subjected to 40,000 bending cycles under electrical load without insulation puncture or wire severance.")]),

    ("is-302-2-6-2009", "IS 302 (Part 2/Sec 6):2009", "Safety of Household Electrical Appliances: Cooking Ranges, Hobs and Ovens", 2009,
     "Electrical", "Electrotechnical / ETD 32", True, "Scheme I (ISI Mark)", "Household Appliances Quality Order",
     ["electric hob manufacturers", "built-in oven plants", "induction cooktop factories"],
     "Mandatory standard for electric cooking ranges, built-in ovens, induction cooktops, and ceramic glass hobs.",
     "Covers glass ceramic impact resistance, spillover liquid ingress, and thermostat cut-offs.",
     ["induction cooktop", "built in oven", "hob spillover test", "ceramic glass impact", "pan detection sensor"],
     [cls("is302-2-6-c15", "Clause 15.2", "Liquid Spillage Over Electric Hob", "0.5 liter saline water spilled over cooking surface; appliance must pass 1500 V dielectric test without insulation breakdown.")]),

    # Batteries & Energy Storage
    ("is-16805-2018", "IS 16805:2018", "Safety of Power Converters for Photovoltaic Power Systems: EMC Requirements", 2018,
     "Electronics & IT", "Electrotechnical / ETD 28", True, "Scheme I (ISI Mark)", "Solar Quality Control Order",
     ["solar inverter factories", "EMC testing laboratories", "PV power converter plants"],
     "Mandatory standard for conducted and radiated electromagnetic emission limits and immunity for solar PV inverters.",
     "Covers CISPR 11 Class A/B emission limits, electrostatic discharge (ESD 8kV air), and lightning surge immunity (4kV).",
     ["solar inverter EMC", "conducted emission", "radiated emission", "surge immunity 4kV", "ESD 8kV", "CISPR 11"],
     [cls("is16805-c6", "Clause 6.1", "Conducted Emissions & Surge Immunity", "Conducted radio interference on AC mains ports shall not exceed quasi-peak limits of CISPR 11; withstand 4.0 kV line-to-earth surge.")]),

    ("is-16270-2014", "IS 16270:2014", "Secondary Cells and Batteries for Solar Photovoltaic (PV) Energy Systems", 2014,
     "Electrical", "Electrotechnical / ETD 11", True, "Scheme I (ISI Mark)", "Solar Energy Quality Control Order",
     ["solar battery manufacturers", "tubular gel battery plants"],
     "Mandatory standard for deep-cycle stationary batteries (lead-acid and gel) used in off-grid solar rooftop installations.",
     "Covers deep discharge cycle endurance (minimum 1500 cycles at 80% DOD) and ampere-hour efficiency.",
     ["solar battery", "deep cycle battery", "tubular gel", "ampere hour efficiency >= 90%", "cycle life 1500 cycles"],
     [cls("is16270-c7", "Clause 7.2", "Endurance in Solar Deep Cycling", "Battery must sustain 1500 charge-discharge cycles at 80% depth of discharge (DOD) retaining >80% initial capacity.")]),

    ("is-15549-2005", "IS 15549:2005", "Stationary Valve Regulated Lead-Acid (VRLA) Batteries — Specification", 2005,
     "Electrical", "Electrotechnical / ETD 11", True, "Scheme I (ISI Mark)", "VRLA Batteries Standards",
     ["VRLA battery plants", "telecom UPS battery manufacturing", "SMF battery factories"],
     "Mandatory standard for Sealed Maintenance Free (SMF) absorbed glass mat (AGM) and gel VRLA batteries for telecom and data centers.",
     "Covers gas recombination efficiency (minimum 95%), thermal runaway prevention, and self-discharge rates.",
     ["VRLA battery", "SMF battery", "AGM battery", "gas recombination >= 95%", "telecom battery"],
     [cls("is15549-c8", "Clause 8.1", "Gas Recombination Efficiency", "Gas recombination efficiency shall not be less than 95.0% under float charge voltage conditions.")]),

    ("is-1651-2013", "IS 1651:2013", "Stationary Cells and Batteries, Lead-Acid Type with Tubular Positive Plates", 2013,
     "Electrical", "Electrotechnical / ETD 11", True, "Scheme I (ISI Mark)", "Batteries Quality Standards",
     ["tubular inverter battery plants", "lead acid battery foundries"],
     "Mandatory standard for long-life tubular lead-acid flooded stationary batteries used in home inverters and power utilities.",
     "Covers spine antimony alloy composition, active material retention gauntlets, and life cycle endurance.",
     ["tubular battery", "inverter battery", "positive tubular plate", "antimony lead spine", "cycle life"],
     [cls("is1651-c7", "Clause 7.1", "Life Cycle Endurance Test", "Battery subjected to life cycles per Table 3; shall achieve minimum 1200 cycles of charge/discharge before capacity drops below 80%.")]),

    ("is-1652-2013", "IS 1652:2013", "Stationary Cells and Batteries, Lead-Acid Type with Plante Positive Plates", 2013,
     "Electrical", "Electrotechnical / ETD 11", True, "Scheme I (ISI Mark)", "Batteries Quality Standards",
     ["pure lead plante battery plants", "power utility DC backup plants"],
     "Specifies long-life pure lead solid cast Plante plate stationary batteries engineered for 25-year service life in thermal power stations.",
     "Covers float charge current, high discharge rates, and container transparency.",
     ["plante battery", "pure lead plate", "25 year design life", "power grid DC backup"],
     [cls("is1652-c6", "Clause 6.1", "High Rate Discharge Performance", "Battery shall deliver 1-minute discharge rate at 3.0 times C10 current maintaining voltage above 1.70 V per cell.")]),

    ("is-7372-1995", "IS 7372:1995", "Lead-Acid Storage Batteries for Motor Vehicles (Four Wheelers)", 1995,
     "Electrical", "Electrotechnical / ETD 11", True, "Scheme I (ISI Mark)", "Automotive Quality Order",
     ["automotive car battery factories", "SLI battery manufacturing"],
     "Mandatory standard for Starting, Lighting and Ignition (SLI) automotive lead-acid batteries for commercial vehicles and cars.",
     "Covers Cold Cranking Amperes (CCA at -18°C), vibration resistance, and reserve capacity in minutes.",
     ["car battery", "automotive SLI", "cold cranking amps CCA", "reserve capacity 80min", "vibration test"],
     [cls("is7372-c6", "Clause 6.2", "Cold Cranking Amperage (CCA at -18°C)", "Battery discharged at rated CCA at -18°C; terminal voltage shall remain above 7.2 V after 30 seconds of continuous cranking.")]),

    ("is-14257-1995", "IS 14257:1995", "Lead-Acid Storage Batteries for Two Wheelers — Specification", 1995,
     "Electrical", "Electrotechnical / ETD 11", True, "Scheme I (ISI Mark)", "Automotive Quality Order",
     ["two wheeler battery plants", "motorcycle battery factories"],
     "Mandatory standard for compact 12V and 6V starting batteries for motorcycles, scooters, and mopeds.",
     "Covers spill-proof vent caps, rapid charge acceptance, and high vibration resistance on Indian road conditions.",
     ["motorcycle battery", "two wheeler battery", "spill proof cap", "vibration test 30Hz", "charge acceptance"],
     [cls("is14257-c5", "Clause 5.1", "Vibration Endurance Test", "Battery vibrated at 30 Hz with 1.5 mm amplitude for 4 hours; no acid leakage, internal plate bridging, or terminal cracking.")]),

    # Solar PV Infrastructure
    ("is-16169-2014", "IS 16169:2014", "Test Procedure for Islanding Prevention Measures for Utility-Interconnected Photovoltaic Inverters", 2014,
     "Electronics & IT", "Electrotechnical / ETD 28", True, "Scheme I (ISI Mark)", "Solar Quality Control Order",
     ["solar inverter testing laboratories", "grid tie testing stations"],
     "Standard laboratory test procedures for islanding protection disconnects in grid-tied solar inverters under tuned RLC resonant loads.",
     "Prescribes testing protocols for anti-islanding trip times (< 2.0 seconds) to safeguard utility line workers.",
     ["anti islanding test", "RLC resonant load", "solar grid inverter", "quality factor Q 1.0", "disconnect <= 2s"],
     [cls("is16169-c4", "Clause 4.1", "Resonant Load Islanding Disconnection Time", "Under perfectly matched resonant load with Quality Factor Q = 1.0, inverter must cease energizing grid within 2.0 seconds.")]),

    ("is-16077-2013", "IS 16077:2013", "Thin-Film Terrestrial Photovoltaic (PV) Modules — Design Qualification and Type Approval", 2013,
     "Electronics & IT", "Electrotechnical / ETD 28", True, "Scheme I (ISI Mark)", "Solar Quality Control Order",
     ["thin film solar panel factories", "CdTe and CIGS module plants"],
     "Mandatory standard for CdTe, CIGS, and amorphous silicon thin-film photovoltaic panels.",
     "Covers wet leakage current test, light soaking stabilization, thermal cycling, and hail impact test (25 mm ice ball).",
     ["thin film solar", "CdTe module", "CIGS panel", "light soaking", "hail test 25mm", "wet leakage current"],
     [cls("is16077-c10", "Clause 10.17", "Hail Impact Resistance Test", "Module impacted at 11 points with 25 mm diameter ice sphere traveling at 23 m/s without glass cracking or power loss.")]),

    ("is-16627-2017", "IS 16627:2017", "Solar Photovoltaic Water Pumping Systems — Specification", 2017,
     "Electrical", "Electrotechnical / ETD 28", True, "Scheme I (ISI Mark)", "PM KUSUM Solar Scheme Order",
     ["solar water pump manufacturers", "submersible agricultural pump plants"],
     "Mandatory standard under PM KUSUM for solar-powered submersible and surface agricultural irrigation pump sets (1 HP to 10 HP).",
     "Covers minimum daily water output (liters per day per watt peak), MPPT efficiency (>98%), and solar tracking.",
     ["solar water pump", "PM KUSUM", "submersible solar pump", "MPPT efficiency 98%", "water output LPD"],
     [cls("is16627-c6", "Clause 6.1", "Daily Water Output Guarantee", "A 5 HP pump powered by 4800 Wp array must deliver minimum 150,000 liters/day from 30m head under standard solar irradiance.")]),

    # IT Hardware & CRS Electronics
    ("is-16333-3-2022", "IS 16333 (Part 3):2022", "Mobile Phone Handsets — Part 3: Indian Language Support Requirements", 2022,
     "Electronics & IT", "Electronics / LITD 16", True, "Compulsory Registration Scheme (CRS)", "MeitY Compulsory Orders",
     ["smartphone manufacturing plants", "feature phone assembly plants", "mobile OS software vendors"],
     "Mandatory MeitY standard requiring all mobile phones sold in India to support reading and input in all 22 official Indian languages.",
     "Specifies font rendering, virtual keypad layout, and SMS transmission for devanagari, tamil, telugu, bengali, etc.",
     ["mobile phone", "Indian language support", "22 scheduled languages", "MeitY mandate", "virtual keyboard"],
     [cls("is16333-3-c4", "Clause 4.1", "Text Input and Display in Indian Languages", "Phone must display and allow keyboard input of full character sets for all 22 scheduled official Indian languages.")]),

    ("is-13252-1-printers", "IS 13252 (Part 1):2010", "Information Technology Equipment: Desktop Printers, Plotters & Scanners", 2010,
     "Electronics & IT", "Electronics / LITD 16", True, "Compulsory Registration Scheme (CRS)", "MeitY Compulsory Orders",
     ["printer manufacturing plants", "inkjet assembly lines", "laser printer factories"],
     "Mandatory safety standard for desktop inkjet printers, commercial laser printers, and architectural CAD plotters under CRS.",
     "Covers heating fuser roller electrical insulation, toner emission, and SELV supply isolation.",
     ["laser printer", "inkjet printer", "plotter", "SELV circuit", "fuser roller safety", "CRS registration"],
     [cls("is13252-p-c4", "Clause 4.2", "Mechanical & Thermal Hazard of Fuser Assembly", "Fuser rollers operating at >180°C must be shielded from operator contact; thermal limiters must prevent paper ignition.")]),

    ("is-13252-1-servers", "IS 13252 (Part 1):2010", "Information Technology Equipment: Automatic Data Processing Machines (Servers)", 2010,
     "Electronics & IT", "Electronics / LITD 16", True, "Compulsory Registration Scheme (CRS)", "MeitY Compulsory Orders",
     ["data center server assembly", "blade server manufacturing", "compute rack plants"],
     "Mandatory CRS standard for enterprise rackmount servers, blade chassis, and cloud computing data center servers.",
     "Covers redundant power supply (CRPS) safety, leakage current under multi-cord connections, and fire enclosure integrity.",
     ["enterprise server", "rackmount server", "data center hardware", "earth leakage current", "fire enclosure"],
     [cls("is13252-s-c5", "Clause 5.1", "Touch Current & Earth Conductor Integrity", "Maximum touch current for industrial high-leakage rack equipment shall not exceed 3.5% with permanent protective earthing.")]),

    ("is-13252-1-adapters", "IS 13252 (Part 1):2010", "Information Technology Equipment: Power Adapters for IT & Mobile Devices", 2010,
     "Electronics & IT", "Electronics / LITD 16", True, "Compulsory Registration Scheme (CRS)", "MeitY Compulsory Orders",
     ["mobile charger factories", "SMPS adapter manufacturing", "laptop charger plants"],
     "Mandatory CRS standard for AC/DC power adapters, USB mobile chargers (GaN and Silicon), and laptop charging bricks.",
     "Covers transformer isolation (3000 V AC withstand), creepage distances, short-circuit protection, and flame-retardant enclosures (V-0).",
     ["mobile charger", "laptop adapter", "SMPS adapter", "creepage 6mm", "V-0 fire retardant", "CRS"],
     [cls("is13252-a-c2", "Clause 2.10", "Primary to Secondary Creepage & Clearance", "Minimum creepage distance of 6.0 mm and clearance of 4.0 mm required across optocouplers and isolation transformers.")]),

    ("is-16242-1-2014", "IS 16242 (Part 1):2014", "Uninterruptible Power Systems (UPS) — Part 1: General and Safety Requirements", 2014,
     "Electronics & IT", "Electronics / LITD 16", True, "Compulsory Registration Scheme (CRS)", "Electronics Quality Control Order",
     ["online UPS manufacturing plants", "home inverter UPS factories"],
     "Mandatory CRS standard for online double-conversion and line-interactive UPS systems from 500 VA to 500 kVA.",
     "Covers battery dc reverse polarity protection, backfeed protection relays, and output overload withstand.",
     ["online UPS", "uninterruptible power supply", "backfeed protection", "battery dc isolation", "CRS"],
     [cls("is16242-1-c4", "Clause 4.3", "Backfeed Protection on Mains Input", "UPS shall prevent hazardous backfeed voltage on input AC terminals within 1.0 second of utility mains failure.")]),

    ("is-13252-1-pos", "IS 13252 (Part 1):2010", "Information Technology Equipment: Point of Sale (POS) Terminals & EDC Machines", 2010,
     "Electronics & IT", "Electronics / LITD 16", True, "Compulsory Registration Scheme (CRS)", "MeitY Compulsory Orders",
     ["POS terminal factories", "payment soundbox assembly", "EDC machine manufacturing"],
     "Mandatory CRS standard for handheld credit card POS terminals, payment soundboxes, and biometric banking micro-ATMs.",
     "Covers lithium battery charging circuits, thermal printer safety, and drop impact resistance.",
     ["POS terminal", "payment soundbox", "EDC machine", "battery protection circuit", "CRS registration"],
     [cls("is13252-pos-c3", "Clause 3.2", "Battery Charging Safety & Overvoltage", "Battery management system (BMS) inside terminal must safely terminate charge when voltage reaches 4.25V per cell.")]),

    ("is-13252-1-cctv", "IS 13252 (Part 1):2010", "Information Technology Equipment: CCTV Cameras and Recorders (DVR/NVR)", 2010,
     "Electronics & IT", "Electronics / LITD 16", True, "Compulsory Registration Scheme (CRS)", "MeitY Compulsory Orders",
     ["CCTV camera manufacturing", "NVR assembly plants", "security surveillance equipment"],
     "Mandatory CRS standard for indoor dome cameras, outdoor bullet IP cameras, and network video recorders (NVR).",
     "Covers Power over Ethernet (PoE 48V) isolation, surge immunity on video ports, and IP66 outdoor weather sealing.",
     ["CCTV camera", "IP camera", "NVR", "PoE safety", "surge protection 4kV", "CRS registration"],
     [cls("is13252-cctv-c4", "Clause 4.1", "PoE Ethernet Port Dielectric Isolation", "Ethernet PoE port shall withstand 1500 V AC dielectric test to chassis earth to protect against lightning transients.")]),

    ("is-13252-1-wearables", "IS 13252 (Part 1):2010", "Information Technology Equipment: Smart Watches and Fitness Trackers", 2010,
     "Electronics & IT", "Electronics / LITD 16", True, "Compulsory Registration Scheme (CRS)", "MeitY Compulsory Orders",
     ["smartwatch assembly lines", "wearable tech manufacturing"],
     "Mandatory CRS standard for wrist-worn smart watches, fitness bands, and continuous physiological monitoring wearables.",
     "Covers skin contact biocompatibility, lithium coin/pouch battery puncture safety, and magnetic charging pin short circuit.",
     ["smart watch", "fitness tracker", "wearable tech", "skin contact biocompatibility", "CRS registration"],
     [cls("is13252-w-c4", "Clause 4.3", "Skin Contact Temperature & Current", "Chassis temperature touching wrist shall not exceed 43°C during maximum compute and fast magnetic charging.")]),

    ("is-13252-1-tablets", "IS 13252 (Part 1):2010", "Information Technology Equipment: Tablet Computers and E-Book Readers", 2010,
     "Electronics & IT", "Electronics / LITD 16", True, "Compulsory Registration Scheme (CRS)", "MeitY Compulsory Orders",
     ["tablet computer assembly plants", "e-reader manufacturing"],
     "Mandatory CRS safety standard for touchscreen tablet computers, educational tablets, and digital e-readers.",
     "Covers tempered cover glass impact, high C-rate battery charging thermals, and electromagnetic emission compliance.",
     ["tablet computer", "e-reader", "touchscreen glass impact", "battery thermal management", "CRS"],
     [cls("is13252-t-c4", "Clause 4.2", "Touchscreen Impact Resistance", "Screen shall withstand steel ball drop test (50 mm diameter ball dropped from 500 mm height) without glass splintering.")]),

    ("is-13252-1-monitors", "IS 13252 (Part 1):2010", "Information Technology Equipment: Visual Display Units / LED Monitors", 2010,
     "Electronics & IT", "Electronics / LITD 16", True, "Compulsory Registration Scheme (CRS)", "MeitY Compulsory Orders",
     ["LED monitor manufacturing", "commercial display panel factories"],
     "Mandatory CRS standard for desktop LED computer monitors, commercial video walls, and interactive touch kiosks up to 65-inch.",
     "Covers power supply creepage, blue light emissions, stability under tilt, and flame retardant back cover plastics.",
     ["LED monitor", "computer screen", "video wall", "display stability 10 degree tilt", "CRS registration"],
     [cls("is13252-m-c4", "Clause 4.1", "Physical Stability Tilt Test", "Monitor mounted on desktop stand shall not overturn when tilted at an angle of 10° in any orientation.")]),

    ("is-15885-2-11-2011", "IS 15885 (Part 2/Sec 11):2011", "Lamp Controlgear: Electronic Step-Down Convertors for Filament Lamps", 2011,
     "Electronics & IT", "Electrotechnical / ETD 23", True, "Compulsory Registration Scheme (CRS)", "Electronics Quality Control Order",
     ["low voltage lighting transformer factories", "halogen lighting converter plants"],
     "Mandatory CRS standard for high frequency electronic step-down convertors delivering 12V supply to halogen and decorative lights.",
     "Covers short circuit protection, radio interference, and high ambient thermal performance (Ta = 50°C).",
     ["electronic transformer", "step down convertor", "12V halogen supply", "short circuit proof", "CRS"],
     [cls("is15885-2-11-c7", "Clause 7.1", "Secondary Output Short-Circuit Test", "Output terminals short-circuited; convertor shall safely trip via internal PTC/fuse without fire hazard.")]),

    ("is-616-audio", "IS 616:2017", "Audio, Video Equipment: Wireless Microphones and Bluetooth PA Audio Systems", 2017,
     "Electronics & IT", "Electronics / LITD 16", True, "Compulsory Registration Scheme (CRS)", "MeitY Compulsory Orders",
     ["PA audio speaker factories", "wireless microphone manufacturing"],
     "Mandatory CRS standard for portable Bluetooth party speakers, commercial public address amplifiers, and wireless microphones.",
     "Covers acoustic sound pressure level limits (<100 dBA), high temperature amplifier heatsinks, and internal battery safety.",
     ["bluetooth speaker", "wireless microphone", "PA amplifier", "sound pressure level <= 100dBA", "CRS"],
     [cls("is616-a-c5", "Clause 5.1", "Maximum Sound Pressure Output Protection", "Personal audio playback through headphone/speaker ports shall not exceed safe listening limit of 100 dBA without user alert.")]),

    ("is-9224-2-1979", "IS 9224 (Part 2):1979", "Low-Voltage Fuses — Specification: Fuses with High Breaking Capacity", 1979,
     "Electrical", "Electrotechnical / ETD 39", True, "Scheme I (ISI Mark)", "LV Switchgear Standards",
     ["high breaking capacity fuse manufacturers", "substation fuse link plants"],
     "Mandatory specification for cartridge fuses with breaking capacity of not less than 80 kA at 415 V.",
     "Covers time-lag and quick-acting fuses for protection of transformers and motor circuits.",
     ["HRC fuse link", "80kA breaking capacity", "fuse carrier", "cartridge fuse link"],
     [cls("is9224-2-c6", "Clause 6.1", "Short-Circuit Breaking Capacity Test", "Fuse links shall clear prospective fault current of 80 kA at 1.1 times rated voltage without arc flash escape.")]),

    ("is-1248-1-2003", "IS 1248 (Part 1):2003", "Direct Acting Indicating Analogue Electrical Measuring Instruments (Ammeters & Voltmeters)", 2003,
     "Electrical", "Electrotechnical / ETD 13", True, "Scheme I (ISI Mark)", "Panel Instruments Standards",
     ["analogue meter manufacturers", "switchboard panel meter plants"],
     "Specifies accuracy classes (Class 0.5, 1.0, 1.5), damping, and overload withstand for moving coil and moving iron panel meters.",
     "Covers AC and DC voltmeters, ammeters, and frequency meters for control switchboards.",
     ["analogue meter", "ammeter", "voltmeter", "moving coil meter", "Class 1.5 accuracy", "panel instrument"],
     [cls("is1248-1-c5", "Clause 5.1", "Intrinsic Accuracy and Overload Limit", "Error at reference conditions shall not exceed ±1.5% of fiducial scale; shall withstand 10-times short-time current overload.")]),

    ("is-302-2-3-electric-iron", "IS 302 (Part 2/Sec 3):2007", "Safety of Household Electrical Appliances: Electric Dry and Steam Irons", 2007,
     "Electrical", "Electrotechnical / ETD 32", True, "Scheme I (ISI Mark)", "Household Appliances Quality Order",
     ["electric iron manufacturing plants", "steam iron factories"],
     "Mandatory safety standard for domestic dry irons, steam irons, and garment steamers.",
     "Covers soleplate temperature limits, thermostat endurance (100,000 cycles), thermal fuse cut-off, and drop impact resistance.",
     ["electric iron", "steam iron", "soleplate temperature", "thermostat endurance", "thermal cut-off"],
     [cls("is302-2-3-c19", "Clause 19.101", "Thermostat Failure & Thermal Fuse Action", "In the event of thermostat contact welding, internal thermal fuse must permanently isolate element before soleplate exceeds 350°C.")])
]
