# Batch 3: Mechanical, Automotive, Safety Gear, Food/Water & Medical (60 Standards)
# Total after Batch 3 = 60 + 65 + 65 + 60 = 250 standards

def cls(cid, num, title, content, test_req=None, mandatory=True):
    c = {
        "id": cid,
        "number": num,
        "title": title,
        "content": content,
        "mandatory": mandatory
    }
    if test_req:
        c["testRequirement"] = test_req
        c["testMethod"] = test_req
    return c

BATCH_3_DATA = [
    # Food & Drinking Water Safety
    ("is-13428-2005", "IS 13428:2005", "Packaged Natural Mineral Water — Specification", 2005,
     "Consumer Goods", "Food & Agriculture / FAD 14", True, "Scheme I (ISI Mark)", "Packaged Water Quality Control Order",
     ["mineral water bottling plants", "spring water packaging units"],
     "Mandatory standard for natural mineral water sourced directly from underground springs without chemical treatment.",
     "Covers total dissolved solids (TDS), mineral limits, zero microbial pathogens, and hygienic bottling.",
     ["natural mineral water", "spring water", "TDS 150-700 mg/l", "microbiological safety", "FSSAI compliance"],
     [cls("is13428-c5", "Clause 5.1", "Microbiological Safety Requirements", "Shall be completely free from E. coli, coliform bacteria, Faecal streptococci, Pseudomonas aeruginosa in 250 ml.")]),

    ("is-10500-2012", "IS 10500:2012", "Drinking Water — Specification (Potable Water)", 2012,
     "Consumer Goods", "Food & Agriculture / FAD 14", True, "Scheme I (ISI Mark)", "Drinking Water Standards",
     ["municipal water utilities", "water purification plants", "RO plant operators"],
     "National drinking water quality benchmark prescribing acceptable and permissible limits for 65 physicochemical parameters.",
     "Covers pH, turbidity, total hardness, fluoride, arsenic, lead, pesticide residues, and coliform limits.",
     ["drinking water", "potable water", "TDS <= 500 mg/l", "fluoride <= 1.0 mg/l", "arsenic <= 0.01 mg/l", "pH 6.5-8.5"],
     [cls("is10500-c4", "Clause 4.1", "Acceptable and Permissible Limits", "TDS acceptable limit 500 mg/l; total hardness 200 mg/l; fluoride 1.0 mg/l; arsenic 0.01 mg/l per Table 1.")]),

    ("is-1165-2002", "IS 1165:2002", "Milk Powder — Specification", 2002,
     "Consumer Goods", "Food & Agriculture / FAD 19", True, "Scheme I (ISI Mark)", "Milk Products Quality Order",
     ["dairy processing plants", "spray drying milk powder units"],
     "Mandatory standard for whole milk powder, skimmed milk powder (SMP), and partly skimmed milk powder.",
     "Covers milk fat (minimum 26% for whole milk), moisture (maximum 4.0%), solubility index, and scorched particles.",
     ["milk powder", "skimmed milk powder SMP", "milk fat >= 26%", "solubility index <= 1.0ml", "FSSAI"],
     [cls("is1165-c5", "Clause 5.1", "Compositional Limits & Solubility", "Whole milk fat >= 26.0% by mass; moisture <= 4.0%; titratable acidity <= 1.2%; total plate count <= 40,000 CFU/g.")]),

    ("is-1166-1986", "IS 1166:1986", "Condensed Milk, Partly Skimmed and Skimmed Condensed Milk — Specification", 1986,
     "Consumer Goods", "Food & Agriculture / FAD 19", True, "Scheme I (ISI Mark)", "Milk Products Quality Order",
     ["sweetened condensed milk plants", "dairy packaging units"],
     "Mandatory standard for sweetened condensed milk, total milk solids (minimum 31.0%), and sucrose content.",
     "Covers vacuum evaporation, sugar addition, bacterial counts, and hermetic tin canning.",
     ["condensed milk", "milk solids >= 31%", "milk fat >= 9%", "sucrose content 40%", "canning safety"],
     [cls("is1166-c5", "Clause 5.1", "Chemical Composition and Milk Solids", "Total milk solids >= 31.0% by mass; milk fat >= 9.0%; sucrose >= 40.0%; yeast and mould <= 10 CFU/g.")]),

    ("is-12220-1987", "IS 12220:1987", "Infant Milk Foods — Specification", 1987,
     "Consumer Goods", "Food & Agriculture / FAD 19", True, "Scheme I (ISI Mark)", "Infant Nutrition Quality Order",
     ["infant formula manufacturers", "baby nutrition pharmaceutical plants"],
     "Mandatory standard for infant milk foods for nourishment of infants up to 6 months.",
     "Covers milk protein, iron enrichment, vitamin additions (A, D, C, B-complex), and strict pesticide residue limits.",
     ["infant milk food", "baby formula", "infant nutrition", "vitamin fortification", "FSSAI baby food"],
     [cls("is12220-c5", "Clause 5.1", "Nutrient Profile & Vitamin Fortification", "Protein 12-16% by mass; milk fat 18-28%; vitamin A >= 350 mcg/100g; iron >= 5.0 mg/100g per Table 1.")]),

    ("is-14433-2007", "IS 14433:2007", "Infant Formula — Specification", 2007,
     "Consumer Goods", "Food & Agriculture / FAD 19", True, "Scheme I (ISI Mark)", "Infant Nutrition Quality Order",
     ["specialty infant nutrition plants", "whey-predominant formula factories"],
     "Mandatory standard for adapted whey-to-casein ratio infant formula replicating human milk nutritional profile.",
     "Covers linoleic acid, alpha-linolenic acid, taurine, nucleotides, choline, and zero pathogenic microbes.",
     ["infant formula", "whey casein ratio 60:40", "DHA ARA", "linoleic acid", "microbial safety zero E coli"],
     [cls("is14433-c5", "Clause 5.2", "Fatty Acid Profile & Essential Nutrients", "Linoleic acid >= 300 mg/100 kcal; whey-to-casein ratio 60:40; Cronobacter sakazakii absent in 100g.")]),

    ("is-15757-2007", "IS 15757:2007", "Follow-Up Formula — Specification", 2007,
     "Consumer Goods", "Food & Agriculture / FAD 19", True, "Scheme I (ISI Mark)", "Infant Nutrition Quality Order",
     ["toddler nutrition manufacturers", "dairy processing plants"],
     "Mandatory standard for follow-up formula for infants aged 6 to 24 months as liquid complementary nutrition.",
     "Covers iron absorption promoters, zinc, iodine, energy density (60-85 kcal/100 ml), and strict heavy metal limits.",
     ["follow up formula", "toddler milk", "energy density", "iron zinc iodine", "infant health"],
     [cls("is15757-c5", "Clause 5.1", "Energy Density and Micronutrients", "Energy 60-85 kcal/100 ml; protein 3-5.5 g/100 kcal; iron >= 1.0 mg/100 kcal; lead <= 0.02 mg/kg.")]),

    ("is-1656-2007", "IS 1656:2007", "Milk Cereal Based Weaning Foods — Specification", 2007,
     "Consumer Goods", "Food & Agriculture / FAD 19", True, "Scheme I (ISI Mark)", "Infant Nutrition Quality Order",
     ["cereal weaning food plants", "baby cereal porridge manufacturing"],
     "Mandatory standard for roller-dried or extruded cereal-milk weaning mixes (wheat, rice, ragi based).",
     "Covers digestibility, crude fiber limits (maximum 1.0%), moisture, and complete absence of aflatoxins.",
     ["weaning food", "cereal milk porridge", "aflatoxin absent", "crude fiber <= 1.0%", "infant cereal"],
     [cls("is1656-c5", "Clause 5.1", "Carbohydrate, Protein & Aflatoxin Limits", "Protein >= 15.0% by mass; fat >= 7.5%; total ash <= 5.0%; aflatoxin B1 shall not exceed 0.5 mcg/kg.")]),

    ("is-15333-2003", "IS 15333:2003", "Processed Cereal Based Complementary Foods for Infants — Specification", 2003,
     "Consumer Goods", "Food & Agriculture / FAD 19", True, "Scheme I (ISI Mark)", "Infant Nutrition Quality Order",
     ["baby food manufacturing", "grain based complementary nutrition units"],
     "Mandatory standard for baby biscuits, rusks, and dry extruded cereal foods intended for infants.",
     "Covers sodium limits (<100 mg/100 kcal), vitamin fortification, and chemical preservative prohibitions.",
     ["baby biscuits", "complementary food", "sodium limit <= 100mg", "no chemical preservatives"],
     [cls("is15333-c5", "Clause 5.2", "Sodium Limit and Texture Safety", "Sodium content shall not exceed 100 mg/100 kcal; food texture must rapidly soften on contact with saliva to prevent choking.")]),

    ("is-515-1959", "IS 515:1959", "Carbolic Soap — Specification", 1959,
     "Chemical & Plastics", "Chemical / CHD 25", True, "Scheme I (ISI Mark)", "Soaps Standards",
     ["disinfectant soap manufacturers", "red carbolic soap factories"],
     "Specifies phenolic carbolic acid content (minimum 0.75%), TFM, and antibacterial germicidal strength for carbolic red soaps.",
     "Covers germicidal soaps for general washing and sanitization.",
     ["carbolic soap", "phenolic acid >= 0.75%", "germicidal soap", "TFM 55%"],
     [cls("is515-c5", "Clause 5.1", "Phenolic Substances & TFM", "Phenolic substances as carbolic acid >= 0.75% by mass; total fatty matter (TFM) >= 55.0% by mass.")]),

    # Personal Protective Equipment & Footwear
    ("is-2925-1984", "IS 2925:1984", "Industrial Safety Helmets — Specification", 1984,
     "Consumer Goods", "Chemical / CHD 8", True, "Scheme I (ISI Mark)", "Safety Helmets Quality Control Order",
     ["safety helmet factories", "HDPE hard hat manufacturing", "construction PPE plants"],
     "Mandatory standard for industrial hard hats and safety helmets used on construction sites, mines, and refineries.",
     "Covers shock absorption (transmitted force <5.0 kN under 5 kg striker dropped from 1 m), penetration resistance, and 2000V electrical insulation.",
     ["safety helmet", "industrial hard hat", "shock absorption < 5kN", "penetration test", "electrical insulation 2000V"],
     [cls("is2925-c6", "Clause 6.1", "Shock Absorption Test", "Transmitted force to headform under 5.0 kg drop striker dropped from 1.0 meter shall not exceed 5.0 kN.")]),

    ("is-15298-1-2011", "IS 15298 (Part 1):2011", "Personal Protective Equipment: Test Methods for Footwear", 2011,
     "Consumer Goods", "Chemical / CHD 8", True, "Scheme I (ISI Mark)", "Footwear Quality Control Order",
     ["footwear testing laboratories", "shoe manufacturing plants"],
     "Standard test procedures for safety shoe impact resistance, toe cap compression, sole bond strength, and slip resistance.",
     "Prescribes mechanical impact apparatus (200 J energy) and compression machines (15 kN load).",
     ["footwear testing", "200J toe impact", "15kN compression", "sole bond test", "slip resistance SATRA"],
     [cls("is15298-1-c5", "Clause 5.1", "Toe Cap Impact Resistance Apparatus", "200 Joule impact energy delivered by steel striker; minimum clearance under toe cap after impact per Table 1.")]),

    ("is-15298-2-2016", "IS 15298 (Part 2):2016", "Personal Protective Equipment: Safety Footwear (200 J Impact)", 2016,
     "Consumer Goods", "Chemical / CHD 8", True, "Scheme I (ISI Mark)", "Footwear Quality Control Order",
     ["safety shoe manufacturers", "steel toe boot factories"],
     "Mandatory standard for industrial safety shoes equipped with 200-Joule steel or composite protective toe caps.",
     "Covers oil-resistant soles, anti-static electrical resistance (100 kOhm to 1000 MOhm), and energy absorption of heel (20 J).",
     ["safety shoe", "steel toe boot", "200 Joule impact", "antistatic footwear", "puncture resistant midsole 1100N"],
     [cls("is15298-2-c5", "Clause 5.3", "Toe Cap Impact and Compression", "Toe cap shall withstand 200 J impact and 15 kN compression load maintaining clearance >= 14 mm for size 8.")]),

    ("is-15298-3-2019", "IS 15298 (Part 3):2019", "Personal Protective Equipment: Protective Footwear (100 J Impact)", 2019,
     "Consumer Goods", "Chemical / CHD 8", True, "Scheme I (ISI Mark)", "Footwear Quality Control Order",
     ["protective shoe manufacturers", "light industrial footwear plants"],
     "Mandatory standard for intermediate protective shoes with 100-Joule toe cap impact rating for logistics and warehousing.",
     "Covers water penetration, upper leather tear strength, and sole flexion durability (30,000 flexes).",
     ["protective footwear", "100 Joule toe impact", "warehouse shoe", "sole flexion 30000 flexes"],
     [cls("is15298-3-c5", "Clause 5.1", "100-Joule Impact Test", "Toe cap subjected to 100 Joule impact energy maintaining specified minimum internal clearance.")]),

    ("is-15298-4-2017", "IS 15298 (Part 4):2017", "Personal Protective Equipment: Occupational Footwear (No Toe Cap)", 2017,
     "Consumer Goods", "Chemical / CHD 8", True, "Scheme I (ISI Mark)", "Footwear Quality Control Order",
     ["work shoes factories", "slip resistant hospital shoe manufacturing"],
     "Mandatory standard for occupational work shoes without toe caps used in hospitality, healthcare, and electronics cleanrooms.",
     "Covers slip resistance on ceramic tile with NaLS detergent and steel floor with glycerol, and heel shock absorption.",
     ["occupational footwear", "slip resistance", "hospital shoes", "heel energy absorption 20J"],
     [cls("is15298-4-c5", "Clause 5.1", "Slip Resistance Coefficient (SRC)", "Coefficient of friction shall be >= 0.32 for forward heel slip on ceramic tile with sodium lauryl sulfate solution.")]),

    # Toys Safety
    ("is-9873-2-2019", "IS 9873 (Part 2):2019", "Safety of Toys — Part 2: Flammability Requirements", 2019,
     "Consumer Goods", "Chemical / CHD 34", True, "Scheme I (ISI Mark)", "Toys Quality Control Order",
     ["plush toy factories", "costume toy manufacturing", "soft toy plants"],
     "Mandatory standard regulating burning rate (<30 mm/s) of beards, wigs, masks, plush toys, and fabric play tents.",
     "Covers flame spread rates to ensure children can safely discard ignited costumes without burn injuries.",
     ["toy flammability", "burning rate <= 30mm/s", "plush toy safety", "costume flammability", "toy QCO"],
     [cls("is9873-2-c4", "Clause 4.1", "Rate of Flame Spread", "Rate of flame spread along soft filled plush toys and disguises shall not exceed 30 mm/s measured per Clause 5.")]),

    ("is-9873-4-2017", "IS 9873 (Part 4):2017", "Safety of Toys: Swings, Slides and Similar Activity Toys for Domestic Use", 2017,
     "Consumer Goods", "Chemical / CHD 34", True, "Scheme I (ISI Mark)", "Toys Quality Control Order",
     ["playground toy factories", "plastic slide and swing manufacturers"],
     "Mandatory standard preventing head and neck entrapment, finger trap pinch points, and tip-over on backyard slides and swings.",
     "Covers dynamic structural strength, stability under 50 kg load, and safety barrier heights.",
     ["toy swing", "toy slide", "head entrapment probe", "finger pinch point", "stability under load"],
     [cls("is9873-4-c4", "Clause 4.3", "Entrapment of Head and Neck", "Completely bound openings must either be smaller than 130mm (torso probe) or larger than 230mm (large head probe).")]),

    ("is-9873-7-2017", "IS 9873 (Part 7):2017", "Safety of Toys: Requirements and Test Methods for Finger Paints", 2017,
     "Consumer Goods", "Chemical / CHD 34", True, "Scheme I (ISI Mark)", "Toys Quality Control Order",
     ["finger paint factories", "art supplies manufacturing for children"],
     "Mandatory standard requiring non-toxic food-grade bittering agents (naringin, denatonium benzoate) to prevent ingestion of finger paints.",
     "Covers restrictions on carcinogenic aromatic amines, azo colorants, and heavy metal limits.",
     ["finger paint", "bittering agent denatonium", "non toxic paint", "azo dye prohibition", "toy safety"],
     [cls("is9873-7-c4", "Clause 4.2", "Taste Bittering Agent Requirement", "Finger paints must contain embittering substance (e.g. denatonium benzoate >= 4 mg/kg) to deter children from swallowing paint.")]),

    ("is-9873-9-2017", "IS 9873 (Part 9):2017", "Safety of Toys: Certain Phthalates in Toys and Childcare Articles", 2017,
     "Consumer Goods", "Chemical / CHD 34", True, "Scheme I (ISI Mark)", "Toys Quality Control Order",
     ["plastic toy manufacturing", "teether and rattle plants"],
     "Mandatory standard restricting 6 hazardous phthalate plasticizers (DEHP, DBP, BBP, DINP, DIDP, DNOP) to <0.1% by mass.",
     "Covers GC-MS laboratory testing of PVC toys, teethers, and soft vinyl bath toys.",
     ["phthalates in toys", "DEHP <= 0.1%", "plasticizer restriction", "teether safety", "GC MS testing"],
     [cls("is9873-9-c4", "Clause 4.1", "Maximum Phthalate Concentration Limit", "The concentration of DEHP, DBP, and BBP individually or combined shall not exceed 0.1% (1000 mg/kg) by mass of plastic material.")]),

    ("is-15644-2006", "IS 15644:2006", "Safety of Electric Toys — Specification", 2006,
     "Consumer Goods", "Electrotechnical / ETD 32", True, "Scheme I (ISI Mark)", "Toys Quality Control Order",
     ["battery operated toy plants", "RC car and drone toy factories"],
     "Mandatory safety standard for battery-powered and transformer-fed electric toys.",
     "Covers maximum operating voltage (<= 24V), battery compartment screw locking, short-circuit fire prevention, and laser safety.",
     ["electric toy", "battery toy", "maximum voltage <= 24V", "battery screw lock", "laser radiation Class 1"],
     [cls("is15644-c7", "Clause 7.1", "Voltage Limits and Battery Compartment", "Electric toys shall operate from safety extra-low voltage not exceeding 24V; battery compartment accessible only via screwdriver.")]),

    # Automotive & Glass
    ("is-2553-1-2018", "IS 2553 (Part 1):2018", "Safety Glass — Specification: Part 1 Architectural, Building and General Uses", 2018,
     "Civil & Construction", "Civil Engineering / CED 5", True, "Scheme I (ISI Mark)", "Safety Glass Quality Control Order",
     ["toughened glass processing plants", "laminated architectural glass factories"],
     "Mandatory standard for toughened (tempered) and laminated safety glass used in building facades, railings, and shower cubicles.",
     "Covers particle fragmentation count (minimum 40 particles in 50x50 mm square), thermal shock, and 45 kg shot bag impact.",
     ["toughened glass", "laminated safety glass", "fragmentation test 40 particles", "shot bag impact 45kg", "building glass"],
     [cls("is2553-1-c6", "Clause 6.1", "Fragmentation Test for Toughened Glass", "Center punch fracture shall yield not less than 40 granular particles within any 50 mm x 50 mm counting area without slivers.")]),

    ("is-2553-2-2019", "IS 2553 (Part 2):2019", "Safety Glass — Specification: Part 2 For Road Transport (Automotive Glass)", 2019,
     "Consumer Goods", "Mechanical / TED 6", True, "Scheme I (ISI Mark)", "Automotive Glass Quality Control Order",
     ["automotive windshield plants", "toughened side window glass factories"],
     "Mandatory standard for car laminated windshields and toughened side/rear door glasses.",
     "Covers 2260 g steel ball drop test from 4.0 m, light transmittance (>70%), 10 kg dummy headform impact, and abrasion resistance.",
     ["automotive glass", "car windshield", "laminated glass", "light transmittance >= 70%", "ball drop test 4m"],
     [cls("is2553-2-c6", "Clause 6.1", "2260g Steel Ball Impact on Windshield", "Ball dropped from 4.0 meters on laminated windshield at -20°C and +40°C; ball must not penetrate glass within 5 seconds.")]),

    ("is-13098-2012", "IS 13098:2012", "Automotive Vehicles — Pneumatic Tyres for Commercial Vehicles — Specification", 2012,
     "Consumer Goods", "Chemical / TED 7", True, "Scheme I (ISI Mark)", "Pneumatic Tyres Quality Control Order",
     ["truck bus radial tyre plants", "commercial vehicle tyre manufacturing"],
     "Mandatory standard for truck and bus radial (TBR) and bias pneumatic tyres.",
     "Covers high speed endurance drum testing (47 hours continuous), tyre plunger energy, and bead unseating resistance.",
     ["commercial tyre", "truck tyre TBR", "endurance drum test", "plunger energy", "tyres QCO"],
     [cls("is13098-c6", "Clause 6.1", "High Speed Endurance Drum Test", "Tyre tested on 1.7m diameter test drum at rated speed/load for 47 hours without tread chunking, ply separation, or bead failure.")]),

    ("is-15633-2005", "IS 15633:2005", "Automotive Vehicles — Pneumatic Tyres for Passenger Car Vehicles — Specification", 2005,
     "Consumer Goods", "Chemical / TED 7", True, "Scheme I (ISI Mark)", "Pneumatic Tyres Quality Control Order",
     ["passenger car radial tyre plants", "PCR tyre factories"],
     "Mandatory standard for tubeless radial car tyres (T, H, V, W, Y speed symbols).",
     "Covers high-speed wheel drum test up to 300 km/h, breaking energy, and tread wear indicators (TWI 1.6 mm).",
     ["car tyre", "passenger car radial PCR", "high speed drum test 240kmh", "tread wear indicator TWI 1.6mm"],
     [cls("is15633-c6", "Clause 6.2", "High-Speed Performance Test", "Tyre rotated under load in steps of 10 km/h every 10 minutes up to declared top speed rating without carcass rupture.")]),

    ("is-15636-2012", "IS 15636:2012", "Automotive Vehicles — Pneumatic Tyres for Two and Three-Wheeled Motor Vehicles", 2012,
     "Consumer Goods", "Chemical / TED 7", True, "Scheme I (ISI Mark)", "Pneumatic Tyres Quality Control Order",
     ["motorcycle tyre manufacturing", "scooter tyre plants"],
     "Mandatory standard for motorcycle, scooter, and auto-rickshaw front and rear tyres.",
     "Covers bead unseating resistance force, plunger breaking energy, and dynamic drum endurance test.",
     ["two wheeler tyre", "motorcycle tyre", "bead unseating resistance", "tyre plunger test"],
     [cls("is15636-c6", "Clause 6.1", "Bead Unseating Resistance Force", "Force required to unseat tyre bead from rim edge shall be not less than specified minimum values per Table 3.")]),

    # Metals & Conductors
    ("is-28-1985", "IS 28:1985", "Copper Strip and Sheet for Electrical Purposes — Specification", 1985,
     "Civil & Construction", "Metallurgical / MTD 8", True, "Scheme I (ISI Mark)", "Copper Products Quality Order",
     ["copper strip rolling mills", "electrical busbar manufacturing"],
     "Mandatory standard for electrolytic tough pitch (ETP) and oxygen-free copper strips (99.90% Cu) used in busbars and motor windings.",
     "Covers electrical conductivity (minimum 100% IACS), tensile strength, and hardness.",
     ["copper strip", "ETP copper 99.9%", "electrical busbar", "conductivity 100% IACS", "busbar copper"],
     [cls("is28-c5", "Clause 5.1", "Electrical Resistivity and Conductivity", "Volume resistivity at 20°C shall not exceed 0.017241 ohm.mm²/m corresponding to 100% IACS conductivity.")]),

    ("is-617-1994", "IS 617:1994", "Aluminium and Aluminium Alloy Ingots and Castings for General Engineering", 1994,
     "Civil & Construction", "Metallurgical / MTD 7", True, "Scheme I (ISI Mark)", "Aluminium Quality Control Order",
     ["aluminium die casting foundries", "alloy ingot manufacturing"],
     "Mandatory standard for primary and secondary aluminium foundry alloys (A6, 4600, LM6, LM24) for automotive engine and structural castings.",
     "Covers chemical composition, gas porosity X-ray limits, and tensile strength of test bars.",
     ["aluminium ingot", "die casting alloy", "LM6", "LM24", "silicon aluminium alloy", "tensile strength 170MPa"],
     [cls("is617-c4", "Clause 4.1", "Chemical Composition and Tensile Properties", "Alloy 4600 (LM6): Silicon 10.0-13.0%, Iron <= 0.6%; tensile strength >= 170 MPa, elongation >= 5.0%.")]),

    ("is-733-1983", "IS 733:1983", "Wrought Aluminium and Aluminium Alloy Bars, Rods and Sections for General Engineering", 1983,
     "Civil & Construction", "Metallurgical / MTD 7", True, "Scheme I (ISI Mark)", "Aluminium Quality Control Order",
     ["aluminium extrusion plants", "architectural aluminium section mills"],
     "Mandatory standard for extruded aluminium alloy 6063 and 6082 bars, angles, and channels (T6 temper).",
     "Covers mechanical strength (yield strength >170 MPa for 6063-T6), Webster hardness, and chemical tolerances.",
     ["aluminium extrusion", "alloy 6063 T6", "architectural aluminium", "yield strength 170MPa", "Webster hardness"],
     [cls("is733-c6", "Clause 6.1", "Mechanical Properties (6063-T6)", "0.2% proof stress >= 170 MPa, tensile strength >= 205 MPa, elongation >= 8% on 50 mm gauge length.")]),

    ("is-737-2008", "IS 737:2008", "Wrought Aluminium and Aluminium Alloy Sheet and Strip for General Engineering", 2008,
     "Civil & Construction", "Metallurgical / MTD 7", True, "Scheme I (ISI Mark)", "Aluminium Quality Control Order",
     ["aluminium sheet rolling mills", "cookware blank manufacturing plants"],
     "Mandatory standard for cold-rolled aluminium sheets (alloys 19000, 31000, 52000) used for pressure cookers, aircraft skin, and facades.",
     "Covers bend test, tensile strength, and deep drawing Erichsen cupping.",
     ["aluminium sheet", "alloy 31000", "cookware sheet", "Erichsen cupping value", "anodizing quality"],
     [cls("is737-c6", "Clause 6.1", "Tensile and 180° Bend Test", "Tensile strength per Table 3; cold bend 180° flat on itself without edge cracking or surface tears.")]),

    ("is-1285-2002", "IS 1285:2002", "Wrought Aluminium and Aluminium Alloy Extruded Round Tube and Hollow Sections", 2002,
     "Civil & Construction", "Metallurgical / MTD 7", True, "Scheme I (ISI Mark)", "Aluminium Quality Control Order",
     ["aluminium tube extrusion plants", "condenser tube manufacturers"],
     "Mandatory standard for extruded aluminium round tubes and hollow profiles for heat exchangers, furniture, and structural frames.",
     "Covers hydraulic internal pressure test (up to 3.0 MPa), flattening test, and dimensional tolerances.",
     ["aluminium tube", "hollow extrusion", "hydraulic proof test", "flattening test"],
     [cls("is1285-c8", "Clause 8.1", "Hydraulic Pressure and Flattening", "Tube tested at internal hydrostatic pressure for 10 seconds; tube section flattened between plates to 50% diameter without cracking.")]),

    ("is-282-1982", "IS 282:1982", "Hard-Drawn Aluminium Conductors for Overhead Transmission Purposes (AAC)", 1982,
     "Electrical", "Electrotechnical / ETD 37", True, "Scheme I (ISI Mark)", "Conductors Quality Control Order",
     ["overhead conductor factories", "wire stranding plants"],
     "Mandatory standard for solid and stranded All-Aluminium Conductors (AAC) for power transmission lines.",
     "Covers wire tensile breaking load, wrapping test, and electrical resistance at 20°C.",
     ["AAC conductor", "all aluminium conductor", "overhead power line", "tensile breaking load", "wrapping test"],
     [cls("is282-c6", "Clause 6.1", "Tensile Breaking Load & Electrical Resistance", "Individual wire tensile strength >= 160 to 200 MPa; maximum DC resistance at 20°C per Table 2.")]),

    ("is-398-1-1996", "IS 398 (Part 1):1996", "Aluminium Conductors for Overhead Transmission: Part 1 Aluminium Stranded Conductors", 1996,
     "Electrical", "Electrotechnical / ETD 37", True, "Scheme I (ISI Mark)", "Conductors Quality Control Order",
     ["transmission line conductor plants", "cable manufacturing factories"],
     "Mandatory standard for stranded aluminium conductors (AAC) with uniform lay ratio and wire count (7, 19, 37 strands).",
     "Covers lay length, joints in wires, and total breaking load of conductor assembly.",
     ["stranded aluminium conductor", "lay ratio", "7 strand conductor", "tensile breaking load"],
     [cls("is398-1-c7", "Clause 7.2", "Conductor Breaking Load", "Rated breaking load of stranded conductor shall be calculated as 95% of sum of individual wire breaking strengths.")]),

    ("is-398-2-1996", "IS 398 (Part 2):1996", "Aluminium Conductor, Galvanized Steel-Reinforced (ACSR) — Specification", 1996,
     "Electrical", "Electrotechnical / ETD 37", True, "Scheme I (ISI Mark)", "Conductors Quality Control Order",
     ["ACSR conductor plants", "high voltage power grid conductor factories"],
     "Mandatory standard for ACSR conductors (Dog, Panther, Zebra, Moose) combining high-conductivity aluminium with high-tensile steel core.",
     "Covers zinc coating on steel core wires, torsion test (minimum 18 twists), and rated breaking strength.",
     ["ACSR conductor", "Panther Moose Zebra", "galvanized steel core", "torsion test 18 twists", "high voltage transmission"],
     [cls("is398-2-c7", "Clause 7.1", "Torsion and Zinc Coating on Core Wire", "Galvanized steel core wire must withstand minimum 18 twists in torsion; zinc coating mass >= 240 g/m².")]),

    ("is-398-4-1994", "IS 398 (Part 4):1994", "Aluminium Alloy Stranded Conductors (AAAC) — Specification", 1994,
     "Electrical", "Electrotechnical / ETD 37", True, "Scheme I (ISI Mark)", "Conductors Quality Control Order",
     ["AAAC conductor plants", "coastal power distribution line manufacturers"],
     "Mandatory standard for Al-Mg-Si heat-treated alloy conductors (AAAC) offering high corrosion resistance in coastal areas.",
     "Covers electrical conductivity (minimum 52.5% IACS) and high tensile strength (minimum 295 MPa).",
     ["AAAC conductor", "all aluminium alloy conductor", "coastal transmission", "tensile strength 295MPa", "conductivity 52.5% IACS"],
     [cls("is398-4-c6", "Clause 6.1", "Mechanical and Electrical Properties", "Individual alloy wire tensile strength >= 295 MPa; electrical resistivity at 20°C <= 0.0328 ohm.mm²/m.")]),

    ("is-319-2007", "IS 319:2007", "Free Cutting Brass Bars, Rods and Sections — Specification", 2007,
     "Civil & Construction", "Metallurgical / MTD 8", True, "Scheme I (ISI Mark)", "Brass Quality Control Order",
     ["brass extrusion units", "CNC turned parts manufacturing", "plumbing brassware factories"],
     "Mandatory standard for leaded free-cutting brass (CuZn39Pb3, Grade 1 to 3) for high-speed automated machining.",
     "Covers machinability index (100%), copper content (56.0-59.0%), lead (2.0-3.5%), and mercurous nitrate crack test.",
     ["free cutting brass", "brass rod", "CuZn39Pb3", "machinability 100%", "mercurous nitrate test"],
     [cls("is319-c6", "Clause 6.2", "Mercurous Nitrate Stress Corrosion Test", "Extruded brass rods immersed in mercurous nitrate solution for 30 minutes without developing intergranular stress cracks.")]),

    ("is-410-1977", "IS 410:1977", "Cold Rolled Brass Sheet, Strip and Foil — Specification", 1977,
     "Civil & Construction", "Metallurgical / MTD 8", True, "Scheme I (ISI Mark)", "Brass Quality Control Order",
     ["brass strip rolling mills", "electrical terminal stamping units"],
     "Mandatory standard for 70/30 cartridge brass and 63/37 cold-rolled brass strips for electrical socket clips and radiator fins.",
     "Covers grain size, Vickers hardness, tensile elongation, and deep drawing properties.",
     ["brass sheet", "cartridge brass 70/30", "brass strip", "Vickers hardness", "electrical contact stamping"],
     [cls("is410-c5", "Clause 5.1", "Tensile Strength & Grain Size (Annealed)", "70/30 brass annealed: tensile strength 300 to 380 MPa, elongation >= 50%, average grain size 0.025 to 0.050 mm.")]),

    ("is-1566-1982", "IS 1566:1982", "Hard-Drawn Steel Wire Fabric for Concrete Reinforcement (Welded Wire Mesh)", 1982,
     "Civil & Construction", "Metallurgical / MTD 4", True, "Scheme I (ISI Mark)", "Steel Quality Control Order",
     ["welded wire mesh plants", "BRC fabric factories", "precast RCC mesh manufacturing"],
     "Mandatory standard for machine-welded wire mesh sheets and rolls used in RCC slabs, precast pipes, and road pavements.",
     "Covers weld shear strength (minimum 25% of wire tensile strength), mesh squareness, and wire tensile limits.",
     ["welded wire mesh", "steel wire fabric", "weld shear strength", "BRC mesh", "RCC slab reinforcement"],
     [cls("is1566-c7", "Clause 7.1", "Weld Cross Joint Shear Strength", "Shear strength of electrical resistance weld at cross wire intersection shall be not less than 25% of nominal wire tensile strength.")]),

    # Gas Cylinders & Fire Safety
    ("is-2825-1969", "IS 2825:1969", "Code for Unfired Pressure Vessels — Design, Construction and Inspection", 1969,
     "Civil & Construction", "Mechanical / MED 22", True, "Scheme I (ISI Mark)", "PESO Pressure Vessels Regulations",
     ["pressure vessel fabrication shops", "chemical reactor manufacturers", "boiler factories"],
     "National design code for unfired cylindrical and spherical pressure vessels, joint efficiency, and hydrostatic proof test.",
     "Covers shell thickness calculations, weld radiography, head dishing (torispherical/ellipsoidal), and stress relieving.",
     ["pressure vessel", "unfired vessel", "PESO", "radiography test", "hydrostatic test 1.5x", "post weld heat treatment"],
     [cls("is2825-c6", "Clause 6.1", "Hydrostatic Proof Test Pressure", "Vessel subjected to hydrostatic test pressure equal to 1.3 to 1.5 times maximum design pressure for at least 30 minutes without leakage.")]),

    ("is-3196-1-2013", "IS 3196 (Part 1):2013", "Welded Low Carbon Steel Cylinders for Low Pressure Liquefiable Gases (LPG)", 2013,
     "Consumer Goods", "Mechanical / MED 16", True, "Scheme I (ISI Mark)", "PESO Gas Cylinders Rules",
     ["domestic LPG cylinder factories", "14.2 kg gas cylinder manufacturing"],
     "Mandatory standard for 14.2 kg and 19 kg domestic/commercial LPG cylinders manufactured from high-strength micro-alloyed steel.",
     "Covers burst pressure test (minimum 4.0 MPa), water jacket volumetric expansion test, and seam weld radiography.",
     ["LPG cylinder", "14.2 kg cylinder", "burst pressure 4MPa", "water jacket expansion test", "PESO approval"],
     [cls("is3196-1-c7", "Clause 7.1", "Hydrostatic Stretch and Bursting Pressure", "Cylinder volumetric permanent expansion <= 10% under 2.5 MPa; minimum hydrostatic bursting pressure shall not be less than 4.0 MPa.")]),

    ("is-3196-2-2006", "IS 3196 (Part 2):2006", "Welded Low Carbon Steel Cylinders for Low Pressure Liquefiable Gases: Above 5L", 2006,
     "Consumer Goods", "Mechanical / MED 16", True, "Scheme I (ISI Mark)", "PESO Gas Cylinders Rules",
     ["industrial LPG cylinder plants", "commercial cylinder factories"],
     "Mandatory standard for commercial 35 kg, 47.5 kg, and bulk refrigerant gas cylinders exceeding 5 liter water capacity.",
     "Covers weld root bend tests, circular seam submerged arc welding, and heat treatment normalization.",
     ["commercial LPG cylinder", "47.5 kg cylinder", "refrigerant cylinder", "weld bend test", "normalizing furnace"],
     [cls("is3196-2-c6", "Clause 6.1", "Heat Treatment and Weld Root Bend", "All cylinders normalized in furnace at (900 ± 20)°C; circumferential weld root bend 180° around former without crack.")]),

    ("is-7285-1-2018", "IS 7285 (Part 1):2018", "Refillable Seamless Steel Gas Cylinders: Normalized Steel Cylinders", 2018,
     "Consumer Goods", "Mechanical / MED 16", True, "Scheme I (ISI Mark)", "Gas Cylinders Rules PESO",
     ["seamless oxygen cylinder plants", "CNG cylinder manufacturing"],
     "Mandatory standard for seamless hot-spun gas cylinders for industrial oxygen, nitrogen, argon, and hydrogen at 150-200 bar.",
     "Covers ultrasonic flaw inspection of seamless shell, flattening test, and hydrostatic proof test at 250 bar.",
     ["seamless gas cylinder", "oxygen cylinder", "CNG cylinder", "ultrasonic test 100%", "proof pressure 250 bar"],
     [cls("is7285-1-c8", "Clause 8.1", "Hydrostatic Proof Test and Volumetric Expansion", "Cylinder tested at 250 bar test pressure; permanent volumetric expansion shall not exceed 10% of total expansion.")]),

    ("is-7285-2-2017", "IS 7285 (Part 2):2017", "Refillable Seamless Steel Gas Cylinders: Quenched and Tempered Steel (Up to 300 bar)", 2017,
     "Consumer Goods", "Mechanical / MED 16", True, "Scheme I (ISI Mark)", "Gas Cylinders Rules PESO",
     ["CNG cascade cylinder plants", "high pressure gas cylinder manufacturing"],
     "Mandatory standard for quenched and tempered high-strength Cr-Mo alloy steel cylinders operating up to 300 bar.",
     "Covers low temperature Charpy V-notch impact test (-40°C), burst pressure, and cyclic fatigue testing (12,000 cycles).",
     ["quenched and tempered cylinder", "Cr Mo alloy cylinder", "cyclic fatigue 12000 cycles", "burst ratio >= 1.6"],
     [cls("is7285-2-c9", "Clause 9.1", "Cyclic Pressure Fatigue Test", "Cylinder subjected to 12,000 hydraulic pressure cycles between atmospheric and 200 bar without leak or structural rupture.")]),

    ("is-15100-2001", "IS 15100:2001", "Multifunction Valves for LPG Cylinders — Specification", 2001,
     "Consumer Goods", "Mechanical / MED 16", True, "Scheme I (ISI Mark)", "Gas Valves Quality Control Order",
     ["LPG cylinder valve factories", "brass valve forging units"],
     "Mandatory standard for self-closing Compact 25.6 mm valves fitted on 14.2 kg household domestic LPG cylinders.",
     "Covers internal excess flow valve, pressure relief valve, seal leak tightness under 1.7 MPa pneumatic pressure, and 10,000 opening cycles.",
     ["LPG valve", "cylinder valve", "pressure relief valve PRV", "pneumatic leak test", "10000 cycles endurance"],
     [cls("is15100-c6", "Clause 6.1", "Pneumatic Leak Tightness Test", "Valve submerged in water under 1.7 MPa nitrogen gas pressure for 1 minute; zero air bubble leakage permitted.")]),

    ("is-8776-2003", "IS 8776:2003", "Valve Fittings for Gas Cylinders — Specification", 2003,
     "Consumer Goods", "Mechanical / MED 16", True, "Scheme I (ISI Mark)", "Gas Valves Quality Control Order",
     ["industrial gas valve plants", "oxygen cylinder valve manufacturing"],
     "Mandatory standard for wheel-operated brass valves for industrial and medical gas cylinders (Oxygen, Nitrogen, CO2, Argon).",
     "Covers taper thread dimensions, safety burst disc diaphragms, and operating torque endurance.",
     ["gas cylinder valve", "medical oxygen valve", "burst disc", "taper thread", "handwheel torque"],
     [cls("is8776-c5", "Clause 5.1", "Safety Burst Disc Rupture Pressure", "Bursting disc fitted to valve shall safely rupture between 110% and 130% of cylinder hydrostatic test pressure.")]),

    ("is-15683-2018", "IS 15683:2018", "Portable Fire Extinguishers — Performance and Construction (Clean Agent, Powder, Foam)", 2018,
     "Consumer Goods", "Civil Engineering / CED 22", True, "Scheme I (ISI Mark)", "Fire Extinguishers Quality Order",
     ["fire extinguisher manufacturing plants", "clean agent fire equipment factories"],
     "Mandatory standard for portable dry chemical powder (ABC), mechanical foam (AFFF), water, and clean agent fire extinguishers.",
     "Covers fire rating tests (Class 1A to 20A wood crib fire, Class 21B to 233B heptane fuel fire), burst pressure, and discharge range.",
     ["fire extinguisher", "ABC powder extinguisher", "fire rating 4A 55B", "burst pressure 5.5MPa", "discharge range 6m"],
     [cls("is15683-c7", "Clause 7.1", "Fire Test Rating (Class A Wood Crib)", "4A rated extinguisher must completely extinguish standard 4A wood crib test fire of 120 wooden sticks within discharge time.")]),

    ("is-2171-1999", "IS 2171:1999", "Dry Powder Fire Extinguishers (Cartridge and Stored Pressure) — Specification", 1999,
     "Consumer Goods", "Civil Engineering / CED 22", True, "Scheme I (ISI Mark)", "Fire Extinguishers Standards",
     ["dry powder extinguisher plants", "CO2 cartridge manufacturing"],
     "Specifies construction, minimum 85% discharge of contents within 15 seconds, and 2.5 MPa hydrostatic pressure withstand.",
     "Covers sodium bicarbonate and monoammonium phosphate based industrial dry chemical extinguishers.",
     ["dry powder extinguisher", "stored pressure", "CO2 gas cartridge", "discharge time 15s", "hydrostatic test 2.5MPa"],
     [cls("is2171-c6", "Clause 6.1", "Discharge Performance and Time", "Extinguisher must discharge not less than 85% of total chemical powder within 15 to 25 seconds continuously.")]),

    ("is-16018-2012", "IS 16018:2012", "Wheeled Fire Extinguishers — Performance and Construction", 2012,
     "Consumer Goods", "Civil Engineering / CED 22", True, "Scheme I (ISI Mark)", "Fire Extinguishers Standards",
     ["trolley fire extinguisher plants", "airport fire equipment manufacturing"],
     "Mandatory standard for large mobile wheeled fire extinguishers (25 kg to 150 kg dry powder and 50 L mechanical foam).",
     "Covers carriage towability at 20 km/h, 5.0 meter discharge hose, and large industrial flammable liquid fire ratings (233B).",
     ["wheeled extinguisher", "trolley fire extinguisher 50kg", "large fire rating 233B", "towing test 20kmh"],
     [cls("is16018-c6", "Clause 6.2", "High Capacity Flammable Liquid Fire (233B)", "Wheeled extinguisher must completely knock down and extinguish 233B circular fuel tray fire within 60 seconds.")]),

    ("is-13849-1993", "IS 13849:1993", "Portable Fire Extinguisher, Carbon Dioxide Type — Specification", 1993,
     "Consumer Goods", "Civil Engineering / CED 22", True, "Scheme I (ISI Mark)", "Fire Extinguishers Standards",
     ["CO2 fire extinguisher plants", "electrical substation fire safety"],
     "Mandatory standard for 2 kg, 3 kg, and 4.5 kg CO2 fire extinguishers with non-conductive discharge horn for live electrical equipment.",
     "Covers seamless steel cylinder (tested to 250 bar), discharge horn frostbite protection, and Class B/C electrical fire suppression.",
     ["CO2 fire extinguisher", "electrical fire safety", "discharge horn frostbite", "cylinder pressure 250 bar"],
     [cls("is13849-c5", "Clause 5.1", "Electrical Non-Conductivity Test", "Discharge stream directed at 100 kV high voltage metallic plate at 1.0 meter distance; leakage current through horn <= 0.5 mA.")]),

    # Medical Equipment, Masks & Healthcare
    ("is-10245-2-1994", "IS 10245 (Part 2):1994", "Respiratory Protective Devices: Open-Circuit Self-Contained Breathing Apparatus (SCBA)", 1994,
     "Consumer Goods", "Chemical / CHD 8", True, "Scheme I (ISI Mark)", "Respiratory Safety Equipment Standards",
     ["SCBA breathing apparatus plants", "firefighter PPE manufacturing"],
     "Mandatory standard for compressed air SCBA sets used by firefighters, chemical spill response teams, and mine rescue crews.",
     "Covers breathing resistance, positive pressure face mask seal, audible low pressure warning whistle, and flame engulfment.",
     ["SCBA", "breathing apparatus", "firefighter mask", "positive pressure 300 bar", "warning whistle 55 bar"],
     [cls("is10245-2-c7", "Clause 7.1", "Breathing Resistance & Warning Whistle", "Inhalation breathing resistance <= 3.0 mbar; audible alarm whistle must sound continuously when cylinder drops below 55 bar.")]),

    ("is-9473-2002", "IS 9473:2002", "Respiratory Protective Devices — Filtering Half Masks (N95 / FFP2) — Specification", 2002,
     "Consumer Goods", "Chemical / CHD 8", True, "Scheme I (ISI Mark)", "Masks Quality Control Order",
     ["N95 mask manufacturing plants", "particulate respirator factories"],
     "Mandatory standard for FFP1 (80%), FFP2 (94% / N95 equivalent), and FFP3 (99%) particulate filtering half masks.",
     "Covers sodium chloride particulate penetration, paraffin oil aerosol penetration, breathing resistance, and flammability.",
     ["N95 mask", "FFP2 respirator", "filtration efficiency >= 94%", "breathing resistance <= 2.4 mbar", "paraffin oil aerosol"],
     [cls("is9473-c6", "Clause 6.1", "Sodium Chloride & Paraffin Oil Aerosol Penetration", "Total penetration of NaCl and paraffin oil aerosols through FFP2 filter mask shall not exceed 6.0% (94% efficiency).")]),

    ("is-16289-2014", "IS 16289:2014", "Medical Textiles — Surgical Face Masks — Specification", 2014,
     "Consumer Goods", "Textiles / TXD 36", True, "Scheme I (ISI Mark)", "Medical Textiles Standards",
     ["3-ply surgical mask plants", "medical PPE manufacturing"],
     "Mandatory standard for 3-ply disposable surgical face masks (Class I, II, IIR) used in hospital operating theaters.",
     "Covers Bacterial Filtration Efficiency (BFE >= 98%), sub-micron particulate filtration (PFE >= 95%), and splash synthetic blood resistance.",
     ["surgical mask", "3 ply mask", "bacterial filtration BFE >= 98%", "synthetic blood splash 120 mmHg", "meltblown fabric"],
     [cls("is16289-c5", "Clause 5.1", "Bacterial Filtration Efficiency (BFE)", "BFE tested with Staphylococcus aureus aerosol shall not be less than 98.0% for Class II and Class IIR masks.")]),

    ("is-17334-2019", "IS 17334:2019", "Medical Textiles — Coveralls for Healthcare Workers — Specification", 2019,
     "Consumer Goods", "Textiles / TXD 36", True, "Scheme I (ISI Mark)", "Medical PPE Standards",
     ["PPE coverall factories", "seam tape sealing plants", "medical protective suit manufacturing"],
     "Mandatory standard for viral barrier healthcare coveralls protecting doctors and nurses from infectious biological fluids.",
     "Covers synthetic blood penetration resistance (Class 3), seam tape seal integrity, and moisture vapor transmission rate (MVTR).",
     ["PPE coverall", "medical protective suit", "synthetic blood penetration", "seam heat seal tape", "viral barrier"],
     [cls("is17334-c5", "Clause 5.1", "Synthetic Blood Penetration Resistance", "Fabric and taped seams shall resist synthetic blood penetration at 14 kPa hydrostatic pressure per ISO 16603 Class 3.")]),

    ("is-13422-1992", "IS 13422:1992", "Medical Gloves: Single-Use Sterile Rubber Surgical Gloves — Specification", 1992,
     "Consumer Goods", "Chemical / CHD 9", True, "Scheme I (ISI Mark)", "Medical Devices Quality Order",
     ["latex surgical glove factories", "nitrile medical glove manufacturing"],
     "Mandatory standard for sterile natural rubber latex surgical gloves used in invasive surgical procedures.",
     "Covers tensile strength (minimum 24 MPa unaged), elongation at break (minimum 750%), water leak test, and sterility verification.",
     ["surgical gloves", "sterile latex gloves", "tensile strength 24MPa", "water leak 1000ml", "elongation 750%"],
     [cls("is13422-c6", "Clause 6.1", "Water Leak Impermeability Test", "Gloves filled with 1000 ml water; zero droplet pinhole leakage permitted per AQL 1.5 sampling inspection.")]),

    ("is-15354-2003", "IS 15354:2003", "Single-Use Sterile Rubber Examination Gloves — Specification", 2003,
     "Consumer Goods", "Chemical / CHD 9", True, "Scheme I (ISI Mark)", "Medical Devices Quality Order",
     ["examination glove plants", "powder free nitrile glove factories"],
     "Mandatory standard for medical examination gloves used during clinical diagnostics and outpatient healthcare.",
     "Covers biocompatibility, powder-free residue limits (<2 mg per glove), tensile strength (14 MPa), and freedom from pinholes.",
     ["examination gloves", "nitrile gloves", "powder free <= 2mg", "water leak test AQL 2.5", "medical glove"],
     [cls("is15354-c6", "Clause 6.1", "Pinhole Freedom and Powder Residue", "Pinhole AQL 2.5; total powder mass for powder-free examination gloves shall not exceed 2.0 mg per glove.")]),

    ("is-10263-1982", "IS 10263:1982", "Clinical Thermometers (Liquid-in-Glass) — Specification", 1982,
     "Consumer Goods", "Mechanical / PGD 25", True, "Scheme I (ISI Mark)", "Medical Thermometers Standards",
     ["glass thermometer factories", "mercury/alcohol clinical thermometer plants"],
     "Mandatory standard for liquid-in-glass clinical maximum thermometers measuring human body temperature from 35.0°C to 42.0°C.",
     "Covers maximum permissible error (±0.1°C), constriction tube reset, and thermal shock durability.",
     ["clinical thermometer", "mercury thermometer", "maximum error ±0.1C", "constriction tube", "scale 35 to 42C"],
     [cls("is10263-c5", "Clause 5.1", "Maximum Permissible Error & Constriction", "Error between 35.5°C and 42.0°C shall not exceed ±0.1°C; constriction must maintain reading until shaken down.")]),

    ("is-15907-2010", "IS 15907:2010", "Digital Clinical Thermometers — Specification", 2010,
     "Consumer Goods", "Electronics / LITD 16", True, "Scheme I (ISI Mark)", "Medical Electronics Standards",
     ["digital thermometer assembly lines", "infrared thermometer factories"],
     "Mandatory standard for electronic digital contact and infrared forehead clinical thermometers.",
     "Covers electronic thermistor accuracy (±0.1°C between 35°C and 42°C), waterproof probe tip, low battery alert, and self-test verification.",
     ["digital thermometer", "electronic thermometer", "accuracy ±0.1C", "infrared thermometer", "waterproof probe"],
     [cls("is15907-c5", "Clause 5.1", "Laboratory Measurement Accuracy", "Digital readout error calibrated in precision water bath shall not exceed ±0.1°C across 35.5°C to 42.0°C clinical range.")]),

    ("is-13450-1-2018", "IS 13450 (Part 1):2018", "Medical Electrical Equipment — Part 1: General Requirements for Basic Safety", 2018,
     "Consumer Goods", "Electrotechnical / ETD 23", True, "Scheme I (ISI Mark)", "Medical Electrical Equipment Order",
     ["medical device manufacturing", "patient monitoring system plants", "dialysis machine assembly"],
     "National safety code for medical electrical systems: patient leakage current (<10 uA for Type CF), earth continuity, and defibrillation protection.",
     "Applies to all electro-medical diagnostic and therapeutic equipment.",
     ["medical device safety", "patient leakage current < 10uA", "Type CF applied part", "defibrillator proof"],
     [cls("is13450-1-c8", "Clause 8.7", "Patient Auxiliary and Leakage Currents", "Patient leakage current to earth shall not exceed 10 microamperes under normal condition for Type CF cardiac floating parts.")]),

    ("is-13450-2-24-2018", "IS 13450 (Part 2/Sec 24):2018", "Medical Electrical Equipment: Particular Requirements for Infusion Pumps", 2018,
     "Consumer Goods", "Electrotechnical / ETD 23", True, "Scheme I (ISI Mark)", "Medical Electrical Equipment Order",
     ["syringe pump manufacturers", "volumetric infusion pump factories"],
     "Mandatory standard for volumetric infusion pumps and syringe drivers used in intensive care units (ICU).",
     "Covers occlusion alarm pressure detection, anti-free-flow protection, air-in-line bubble detection, and volumetric dosage accuracy (±5%).",
     ["infusion pump", "syringe pump", "air in line detector", "occlusion pressure alarm", "flow accuracy ±5%"],
     [cls("is13450-2-24-c201", "Clause 201.12", "Delivery Accuracy and Air-in-Line Alarm", "Volumetric flow rate accuracy within ±5%; ultrasonic detector must trigger alarm for air bubbles >= 50 microliters.")]),

    ("is-13450-2-2-2018", "IS 13450 (Part 2/Sec 2):2018", "Medical Electrical Equipment: High Frequency Surgical Equipment (Electrosurgical Units)", 2018,
     "Consumer Goods", "Electrotechnical / ETD 23", True, "Scheme I (ISI Mark)", "Medical Electrical Equipment Order",
     ["electrosurgical generator plants", "cautery machine factories"],
     "Mandatory safety standard for monopolar and bipolar high-frequency (HF) surgical cutting and coagulation cautery generators.",
     "Covers neutral patient return electrode monitoring (REM contact quality), HF leakage current limits, and spark energy control.",
     ["electrosurgical unit", "cautery machine", "REM return electrode", "HF leakage current <= 150mA", "coagulation"],
     [cls("is13450-2-2-c201", "Clause 201.8", "Neutral Return Electrode Contact Quality", "Return electrode monitor (REM) must cut off HF generator within 50 ms if patient skin contact resistance rises above 150 Ohms.")]),

    ("is-13450-2-25-2018", "IS 13450 (Part 2/Sec 25):2018", "Medical Electrical Equipment: Particular Requirements for Electrocardiographs (ECG)", 2018,
     "Consumer Goods", "Electrotechnical / ETD 23", True, "Scheme I (ISI Mark)", "Medical Electrical Equipment Order",
     ["ECG machine manufacturing plants", "12-lead cardiac diagnostic device plants"],
     "Mandatory standard for diagnostic 12-lead electrocardiographs (ECG machines) and ambulatory holter monitors.",
     "Covers input impedance (minimum 10 MOhm), common mode rejection ratio (CMRR >= 100 dB), and defibrillation overload recovery (<5 seconds).",
     ["ECG machine", "electrocardiograph", "CMRR >= 100dB", "defibrillator recovery <= 5s", "input impedance 10MOhm"],
     [cls("is13450-2-25-c201", "Clause 201.12", "Defibrillator Overload Recovery & CMRR", "ECG baseline trace must return to screen within 5.0 seconds after 5000 V defibrillator discharge; CMRR >= 100 dB.")])
]
